// <auto-generated />
namespace ParvazPardaz.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class chngHostDb_970420_1747 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(chngHostDb_970420_1747));
        
        string IMigrationMetadata.Id
        {
            get { return "201807111318086_chngHostDb_970420_1747"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
