// <auto-generated />
namespace ParvazPardaz.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class chngHostDb_970431_1242 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(chngHostDb_970431_1242));
        
        string IMigrationMetadata.Id
        {
            get { return "201807220813026_chngHostDb_970431_1242"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
