// <auto-generated />
namespace ParvazPardaz.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changeHost_970515_15381 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeHost_970515_15381));
        
        string IMigrationMetadata.Id
        {
            get { return "201808061110022_changeHost_970515_15381"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
