// <auto-generated />
namespace ParvazPardaz.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addTblUserGroup_970501_1131 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTblUserGroup_970501_1131));
        
        string IMigrationMetadata.Id
        {
            get { return "201807230701488_addTblUserGroup_970501_1131"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
