// <auto-generated />
namespace ParvazPardaz.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changeHostDb_970510_1910 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeHostDb_970510_1910));
        
        string IMigrationMetadata.Id
        {
            get { return "201808011440566_changeHostDb_970510_1910"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
