//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParvazPardaz.Resource.Commercial
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Commercials
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Commercials()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ParvazPardaz.Resource.Commercial.Commercials", typeof(Commercials).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        public static string AccountNumber
        {
            get
            {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Account Title.
        /// </summary>
        public static string AccountTitle
        {
            get
            {
                return ResourceManager.GetString("AccountTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add Business Card.
        /// </summary>
        public static string AddBusinessCard
        {
            get
            {
                return ResourceManager.GetString("AddBusinessCard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add Contacts.
        /// </summary>
        public static string AddContacts
        {
            get
            {
                return ResourceManager.GetString("AddContacts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add Financial Account.
        /// </summary>
        public static string AddFinancialAccount
        {
            get
            {
                return ResourceManager.GetString("AddFinancialAccount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address
        {
            get
            {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Admin Confirm Date.
        /// </summary>
        public static string AdminConfirmDate
        {
            get
            {
                return ResourceManager.GetString("AdminConfirmDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Admin Confirmed Full Name.
        /// </summary>
        public static string AdminConfirmFullName
        {
            get
            {
                return ResourceManager.GetString("AdminConfirmFullName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Internet Addresses.
        /// </summary>
        public static string AllInternetAddresses
        {
            get
            {
                return ResourceManager.GetString("AllInternetAddresses", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All Phones.
        /// </summary>
        public static string AllPhones
        {
            get
            {
                return ResourceManager.GetString("AllPhones", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تصویر پشت کارت.
        /// </summary>
        public static string BackPicture
        {
            get
            {
                return ResourceManager.GetString("BackPicture", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        public static string Bank
        {
            get
            {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        public static string BankName
        {
            get
            {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Back of business card.
        /// </summary>
        public static string BusinessCardBack
        {
            get
            {
                return ResourceManager.GetString("BusinessCardBack", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Front of business card.
        /// </summary>
        public static string BusinessCardFront
        {
            get
            {
                return ResourceManager.GetString("BusinessCardFront", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BusinessCards.
        /// </summary>
        public static string BusinessCards
        {
            get
            {
                return ResourceManager.GetString("BusinessCards", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Business Personality.
        /// </summary>
        public static string BusinessPersonality
        {
            get
            {
                return ResourceManager.GetString("BusinessPersonality", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cantacts.
        /// </summary>
        public static string Cantacts
        {
            get
            {
                return ResourceManager.GetString("Cantacts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Card Language.
        /// </summary>
        public static string CardLanguage
        {
            get
            {
                return ResourceManager.GetString("CardLanguage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Card Number.
        /// </summary>
        public static string CardNumber
        {
            get
            {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1st field of card number.
        /// </summary>
        public static string CardNumberField1
        {
            get
            {
                return ResourceManager.GetString("CardNumberField1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 2d field of card number.
        /// </summary>
        public static string CardNumberField2
        {
            get
            {
                return ResourceManager.GetString("CardNumberField2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 3th field of card number.
        /// </summary>
        public static string CardNumberField3
        {
            get
            {
                return ResourceManager.GetString("CardNumberField3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 4th field of card number.
        /// </summary>
        public static string CardNumberField4
        {
            get
            {
                return ResourceManager.GetString("CardNumberField4", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 5th field of card number.
        /// </summary>
        public static string CardNumberField5
        {
            get
            {
                return ResourceManager.GetString("CardNumberField5", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cell Phone.
        /// </summary>
        public static string CellPhone
        {
            get
            {
                return ResourceManager.GetString("CellPhone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City
        {
            get
            {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company
        {
            get
            {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manager name.
        /// </summary>
        public static string CompanyManager
        {
            get
            {
                return ResourceManager.GetString("CompanyManager", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string CompanyName
        {
            get
            {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ContactGroupIdList.
        /// </summary>
        public static string ContactGroupIdList
        {
            get
            {
                return ResourceManager.GetString("ContactGroupIdList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts
        {
            get
            {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Country Code.
        /// </summary>
        public static string CountryCode
        {
            get
            {
                return ResourceManager.GetString("CountryCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email
        {
            get
            {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Financial.
        /// </summary>
        public static string Financial
        {
            get
            {
                return ResourceManager.GetString("Financial", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName
        {
            get
            {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تصویر روی کارت.
        /// </summary>
        public static string FrontPicture
        {
            get
            {
                return ResourceManager.GetString("FrontPicture", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName
        {
            get
            {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender
        {
            get
            {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Geographic Coordinates.
        /// </summary>
        public static string GeographicCoordinates
        {
            get
            {
                return ResourceManager.GetString("GeographicCoordinates", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Internal Code.
        /// </summary>
        public static string InternalCode
        {
            get
            {
                return ResourceManager.GetString("InternalCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Is Admin Confirmed?.
        /// </summary>
        public static string IsAdminConfirmed
        {
            get
            {
                return ResourceManager.GetString("IsAdminConfirmed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string IsSaveToContacts
        {
            get
            {
                return ResourceManager.GetString("IsSaveToContacts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Job Group.
        /// </summary>
        public static string JobGroupId
        {
            get
            {
                return ResourceManager.GetString("JobGroupId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Parent Groups.
        /// </summary>
        public static string jobGroupParent
        {
            get
            {
                return ResourceManager.GetString("jobGroupParent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        public static string JobTitle
        {
            get
            {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName
        {
            get
            {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Legal Personality.
        /// </summary>
        public static string LegalPersonality
        {
            get
            {
                return ResourceManager.GetString("LegalPersonality", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Letter Title.
        /// </summary>
        public static string LetterTitle
        {
            get
            {
                return ResourceManager.GetString("LetterTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bank management.
        /// </summary>
        public static string ManagementBank
        {
            get
            {
                return ResourceManager.GetString("ManagementBank", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Business Card Management.
        /// </summary>
        public static string ManagementBusinessCard
        {
            get
            {
                return ResourceManager.GetString("ManagementBusinessCard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contact groups management.
        /// </summary>
        public static string ManagementContactGroups
        {
            get
            {
                return ResourceManager.GetString("ManagementContactGroups", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contacts management.
        /// </summary>
        public static string ManagementContacts
        {
            get
            {
                return ResourceManager.GetString("ManagementContacts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contacts management  for .
        /// </summary>
        public static string ManagementContactsForUser
        {
            get
            {
                return ResourceManager.GetString("ManagementContactsForUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Internet address types management.
        /// </summary>
        public static string ManagementInternetAddressTypes
        {
            get
            {
                return ResourceManager.GetString("ManagementInternetAddressTypes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Job Groups Management.
        /// </summary>
        public static string ManagementJobGroup
        {
            get
            {
                return ResourceManager.GetString("ManagementJobGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to My Contacts Management.
        /// </summary>
        public static string ManagementMyContacts
        {
            get
            {
                return ResourceManager.GetString("ManagementMyContacts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Financial Accounts Management.
        /// </summary>
        public static string ManagementMyFinancialAccounts
        {
            get
            {
                return ResourceManager.GetString("ManagementMyFinancialAccounts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Phone types management.
        /// </summary>
        public static string ManagementPhoneTypes
        {
            get
            {
                return ResourceManager.GetString("ManagementPhoneTypes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Postal address type management.
        /// </summary>
        public static string ManagementPostalAddressType
        {
            get
            {
                return ResourceManager.GetString("ManagementPostalAddressType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile
        {
            get
            {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Natural Personality.
        /// </summary>
        public static string NaturalPersonality
        {
            get
            {
                return ResourceManager.GetString("NaturalPersonality", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Organization Post.
        /// </summary>
        public static string OrganizationPost
        {
            get
            {
                return ResourceManager.GetString("OrganizationPost", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string Picture
        {
            get
            {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string PostalCode
        {
            get
            {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select at least one group.
        /// </summary>
        public static string RequiredContactGroups
        {
            get
            {
                return ResourceManager.GetString("RequiredContactGroups", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Servcie Description.
        /// </summary>
        public static string ServcieDescription
        {
            get
            {
                return ResourceManager.GetString("ServcieDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Shaba Number.
        /// </summary>
        public static string ShabaNumber
        {
            get
            {
                return ResourceManager.GetString("ShabaNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title
        {
            get
            {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unit Of Measurement.
        /// </summary>
        public static string UnitOfMeasurement
        {
            get
            {
                return ResourceManager.GetString("UnitOfMeasurement", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unit Of Measurement Mangement.
        /// </summary>
        public static string UnitOfMeasurementMangement
        {
            get
            {
                return ResourceManager.GetString("UnitOfMeasurementMangement", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User
        {
            get
            {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website
        {
            get
            {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
    }
}
