//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParvazPardaz.Resource.Book {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Book {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Book() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ParvazPardaz.Resource.Book.Book", typeof(Book).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddServ.
        /// </summary>
        public static string AddServ {
            get {
                return ResourceManager.GetString("AddServ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddServTitle.
        /// </summary>
        public static string AddServTitle {
            get {
                return ResourceManager.GetString("AddServTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult.
        /// </summary>
        public static string Adult {
            get {
                return ResourceManager.GetString("Adult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult Capacity Sold.
        /// </summary>
        public static string AdultCapacitySold {
            get {
                return ResourceManager.GetString("AdultCapacitySold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult Count.
        /// </summary>
        public static string AdultCount {
            get {
                return ResourceManager.GetString("AdultCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult Other Currency Price.
        /// </summary>
        public static string AdultOtherCurrencyPrice {
            get {
                return ResourceManager.GetString("AdultOtherCurrencyPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AgeRange.
        /// </summary>
        public static string AgeRange {
            get {
                return ResourceManager.GetString("AgeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AirlineIATACode.
        /// </summary>
        public static string AirlineIATACode {
            get {
                return ResourceManager.GetString("AirlineIATACode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are Booking.
        /// </summary>
        public static string AreBooking {
            get {
                return ResourceManager.GetString("AreBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AreBookingReport.
        /// </summary>
        public static string AreBookingReport {
            get {
                return ResourceManager.GetString("AreBookingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Title.
        /// </summary>
        public static string BankTitle {
            get {
                return ResourceManager.GetString("BankTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BaseCommission.
        /// </summary>
        public static string BaseCommission {
            get {
                return ResourceManager.GetString("BaseCommission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Country.
        /// </summary>
        public static string BirthCountry {
            get {
                return ResourceManager.GetString("BirthCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date.
        /// </summary>
        public static string Birthdate {
            get {
                return ResourceManager.GetString("Birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Capacity.
        /// </summary>
        public static string BookingCapacity {
            get {
                return ResourceManager.GetString("BookingCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BookNow.
        /// </summary>
        public static string BookNow {
            get {
                return ResourceManager.GetString("BookNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BookNowTour.
        /// </summary>
        public static string BookNowTour {
            get {
                return ResourceManager.GetString("BookNowTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to both.
        /// </summary>
        public static string both {
            get {
                return ResourceManager.GetString("both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buyer.
        /// </summary>
        public static string Buyer {
            get {
                return ResourceManager.GetString("Buyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغو.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        public static string Capacity {
            get {
                return ResourceManager.GetString("Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity Sold.
        /// </summary>
        public static string CapacitySold {
            get {
                return ResourceManager.GetString("CapacitySold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        public static string Cash {
            get {
                return ResourceManager.GetString("Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cellphone.
        /// </summary>
        public static string Cellphone {
            get {
                return ResourceManager.GetString("Cellphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckIn Date Time.
        /// </summary>
        public static string CheckInDateTime {
            get {
                return ResourceManager.GetString("CheckInDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out DateTime.
        /// </summary>
        public static string CheckOutDateTime {
            get {
                return ResourceManager.GetString("CheckOutDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child.
        /// </summary>
        public static string Child {
            get {
                return ResourceManager.GetString("Child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Capacity Sold.
        /// </summary>
        public static string ChildCapacitySold {
            get {
                return ResourceManager.GetString("ChildCapacitySold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Count.
        /// </summary>
        public static string ChildCount {
            get {
                return ResourceManager.GetString("ChildCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Other Currency Price.
        /// </summary>
        public static string ChildOtherCurrencyPrice {
            get {
                return ResourceManager.GetString("ChildOtherCurrencyPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommissionPrice.
        /// </summary>
        public static string CommissionPrice {
            get {
                return ResourceManager.GetString("CommissionPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon.
        /// </summary>
        public static string Coupon {
            get {
                return ResourceManager.GetString("Coupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CouponManagement.
        /// </summary>
        public static string CouponManagement {
            get {
                return ResourceManager.GetString("CouponManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        public static string Credit {
            get {
                return ResourceManager.GetString("Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign.
        /// </summary>
        public static string CurrenySign {
            get {
                return ResourceManager.GetString("CurrenySign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DiscountPercent.
        /// </summary>
        public static string DiscountPercent {
            get {
                return ResourceManager.GetString("DiscountPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dollar Base Price.
        /// </summary>
        public static string DollarBasePrice {
            get {
                return ResourceManager.GetString("DollarBasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En FirstName.
        /// </summary>
        public static string EnFirstName {
            get {
                return ResourceManager.GetString("EnFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En LastName.
        /// </summary>
        public static string EnLastName {
            get {
                return ResourceManager.GetString("EnLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpireDate.
        /// </summary>
        public static string ExpireDate {
            get {
                return ResourceManager.GetString("ExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight DateTime.
        /// </summary>
        public static string FlightDateTime {
            get {
                return ResourceManager.GetString("FlightDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlightNo.
        /// </summary>
        public static string FlightNo {
            get {
                return ResourceManager.GetString("FlightNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlightType.
        /// </summary>
        public static string FlightType {
            get {
                return ResourceManager.GetString("FlightType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FromIATACode.
        /// </summary>
        public static string FromIATACode {
            get {
                return ResourceManager.GetString("FromIATACode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel.
        /// </summary>
        public static string Hotel {
            get {
                return ResourceManager.GetString("Hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Description.
        /// </summary>
        public static string HotelDescription {
            get {
                return ResourceManager.GetString("HotelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Package.
        /// </summary>
        public static string HotelPackage {
            get {
                return ResourceManager.GetString("HotelPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel PackageHotel Room Id.
        /// </summary>
        public static string HotelPackageHotelRoomId {
            get {
                return ResourceManager.GetString("HotelPackageHotelRoomId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Package Id.
        /// </summary>
        public static string HotelPackageId {
            get {
                return ResourceManager.GetString("HotelPackageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Package Title.
        /// </summary>
        public static string HotelPackageTitle {
            get {
                return ResourceManager.GetString("HotelPackageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Room.
        /// </summary>
        public static string HotelRoom {
            get {
                return ResourceManager.GetString("HotelRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Room Title.
        /// </summary>
        public static string HotelRoomTitle {
            get {
                return ResourceManager.GetString("HotelRoomTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infant.
        /// </summary>
        public static string Infant {
            get {
                return ResourceManager.GetString("Infant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infant Capacity Sold.
        /// </summary>
        public static string InfantCapacitySold {
            get {
                return ResourceManager.GetString("InfantCapacitySold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infant Count.
        /// </summary>
        public static string InfantCount {
            get {
                return ResourceManager.GetString("InfantCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infant Other Currency Price.
        /// </summary>
        public static string InfantOtherCurrencyPrice {
            get {
                return ResourceManager.GetString("InfantOtherCurrencyPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is active?.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Date?.
        /// </summary>
        public static string IsDate {
            get {
                return ResourceManager.GetString("IsDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Successful?.
        /// </summary>
        public static string IsSuccessful {
            get {
                return ResourceManager.GetString("IsSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string LogoUrl {
            get {
                return ResourceManager.GetString("LogoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Of Agency Settings.
        /// </summary>
        public static string ManagementAgencySettings {
            get {
                return ResourceManager.GetString("ManagementAgencySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Of Orders.
        /// </summary>
        public static string ManagementOrders {
            get {
                return ResourceManager.GetString("ManagementOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Of Order Types.
        /// </summary>
        public static string ManagementOrderTypes {
            get {
                return ResourceManager.GetString("ManagementOrderTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Capacity.
        /// </summary>
        public static string ManagementRoomCapacity {
            get {
                return ResourceManager.GetString("ManagementRoomCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Of Room Types.
        /// </summary>
        public static string ManagementRoomTypes {
            get {
                return ResourceManager.GetString("ManagementRoomTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Of Tasks.
        /// </summary>
        public static string ManagementTasks {
            get {
                return ResourceManager.GetString("ManagementTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Capacity.
        /// </summary>
        public static string MaximumCapacity {
            get {
                return ResourceManager.GetString("MaximumCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to miladiDate.
        /// </summary>
        public static string miladiDate {
            get {
                return ResourceManager.GetString("miladiDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NationalCode.
        /// </summary>
        public static string NationalCode {
            get {
                return ResourceManager.GetString("NationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NationalCode / PassportNo.
        /// </summary>
        public static string NationalCodePassportNo {
            get {
                return ResourceManager.GetString("NationalCodePassportNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumberRoom.
        /// </summary>
        public static string NumberRoom {
            get {
                return ResourceManager.GetString("NumberRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderDate.
        /// </summary>
        public static string OrderDate {
            get {
                return ResourceManager.GetString("OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string OrderId {
            get {
                return ResourceManager.GetString("OrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderReport.
        /// </summary>
        public static string OrderReport {
            get {
                return ResourceManager.GetString("OrderReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderReportCompany.
        /// </summary>
        public static string OrderReportCompany {
            get {
                return ResourceManager.GetString("OrderReportCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderReportPersonal.
        /// </summary>
        public static string OrderReportPersonal {
            get {
                return ResourceManager.GetString("OrderReportPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Step.
        /// </summary>
        public static string OrderStep {
            get {
                return ResourceManager.GetString("OrderStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oservation Payment Logs.
        /// </summary>
        public static string OservationPaymentLog {
            get {
                return ResourceManager.GetString("OservationPaymentLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Currency.
        /// </summary>
        public static string OtherCurrency {
            get {
                return ResourceManager.GetString("OtherCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Currency Id.
        /// </summary>
        public static string OtherCurrencyId {
            get {
                return ResourceManager.GetString("OtherCurrencyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Currency Price.
        /// </summary>
        public static string OtherCurrencyPrice {
            get {
                return ResourceManager.GetString("OtherCurrencyPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Expiration Date.
        /// </summary>
        public static string PassportExpirationDate {
            get {
                return ResourceManager.GetString("PassportExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Expiration Date must be at least 6 month later.
        /// </summary>
        public static string PassportExpirationDateValidate {
            get {
                return ResourceManager.GetString("PassportExpirationDateValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Exporter Country.
        /// </summary>
        public static string PassportExporterCountry {
            get {
                return ResourceManager.GetString("PassportExporterCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport No.
        /// </summary>
        public static string PassportNo {
            get {
                return ResourceManager.GetString("PassportNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayExpiredDateTime.
        /// </summary>
        public static string PayExpiredDateTime {
            get {
                return ResourceManager.GetString("PayExpiredDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Date.
        /// </summary>
        public static string PaymentDate {
            get {
                return ResourceManager.GetString("PaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Response Code.
        /// </summary>
        public static string PaymentResponseCode {
            get {
                return ResourceManager.GetString("PaymentResponseCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Response Message.
        /// </summary>
        public static string PaymentResponseMessage {
            get {
                return ResourceManager.GetString("PaymentResponseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Unique Number.
        /// </summary>
        public static string PaymentUniqueNumberID {
            get {
                return ResourceManager.GetString("PaymentUniqueNumberID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal.
        /// </summary>
        public static string Personal {
            get {
                return ResourceManager.GetString("Personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;توجه!&lt;/strong&gt; اندازه تصویر باید با عرض &lt;code&gt;200&lt;/code&gt;  و ارتفاع &lt;code&gt;200&lt;/code&gt; پیکسل باشد.
        /// </summary>
        public static string PicSize200x200 {
            get {
                return ResourceManager.GetString("PicSize200x200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreFactor.
        /// </summary>
        public static string PreFactor {
            get {
                return ResourceManager.GetString("PreFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Text.
        /// </summary>
        public static string PrintText {
            get {
                return ResourceManager.GetString("PrintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provisional Booking.
        /// </summary>
        public static string ProvisionalBooking {
            get {
                return ResourceManager.GetString("ProvisionalBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remain Booking Capacity.
        /// </summary>
        public static string RemainBookingCapacity {
            get {
                return ResourceManager.GetString("RemainBookingCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Flight Capacity.
        /// </summary>
        public static string RemainingFlightCapacity {
            get {
                return ResourceManager.GetString("RemainingFlightCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remain Total Capacity.
        /// </summary>
        public static string RemainTotalCapacity {
            get {
                return ResourceManager.GetString("RemainTotalCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation.
        /// </summary>
        public static string Reservation {
            get {
                return ResourceManager.GetString("Reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReservationManagement.
        /// </summary>
        public static string ReservationManagement {
            get {
                return ResourceManager.GetString("ReservationManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reserve.
        /// </summary>
        public static string reserve {
            get {
                return ResourceManager.GetString("reserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReserveDate.
        /// </summary>
        public static string ReserveDate {
            get {
                return ResourceManager.GetString("ReserveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieval.
        /// </summary>
        public static string Retrieval {
            get {
                return ResourceManager.GetString("Retrieval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReturnFlightDateTime.
        /// </summary>
        public static string ReturnFlightDateTime {
            get {
                return ResourceManager.GetString("ReturnFlightDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Type.
        /// </summary>
        public static string RoomType {
            get {
                return ResourceManager.GetString("RoomType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Type Capacity.
        /// </summary>
        public static string RoomTypeCapacity {
            get {
                return ResourceManager.GetString("RoomTypeCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        public static string Rule {
            get {
                return ResourceManager.GetString("Rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sales.
        /// </summary>
        public static string sales {
            get {
                return ResourceManager.GetString("sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected DBL Count.
        /// </summary>
        public static string SelectedDBLCount {
            get {
                return ResourceManager.GetString("SelectedDBLCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected EXT Count.
        /// </summary>
        public static string SelectedEXTCount {
            get {
                return ResourceManager.GetString("SelectedEXTCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Hotel Package.
        /// </summary>
        public static string SelectedHotelPackage {
            get {
                return ResourceManager.GetString("SelectedHotelPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Room Count.
        /// </summary>
        public static string SelectedRoomCount {
            get {
                return ResourceManager.GetString("SelectedRoomCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected SGL Count.
        /// </summary>
        public static string SelectedSGLCount {
            get {
                return ResourceManager.GetString("SelectedSGLCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sellesFlightReports.
        /// </summary>
        public static string sellesFlightReports {
            get {
                return ResourceManager.GetString("sellesFlightReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sellesHotelsReports.
        /// </summary>
        public static string sellesHotelsReports {
            get {
                return ResourceManager.GetString("sellesHotelsReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sellesPassengerReports.
        /// </summary>
        public static string sellesPassengerReports {
            get {
                return ResourceManager.GetString("sellesPassengerReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to financialReport.
        /// </summary>
        public static string SellsReport {
            get {
                return ResourceManager.GetString("SellsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shamsiDate.
        /// </summary>
        public static string shamsiDate {
            get {
                return ResourceManager.GetString("shamsiDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful.
        /// </summary>
        public static string Successful {
            get {
                return ResourceManager.GetString("Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful Payment Logs.
        /// </summary>
        public static string SuccessfulPaymentLogs {
            get {
                return ResourceManager.GetString("SuccessfulPaymentLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel.
        /// </summary>
        public static string Tel {
            get {
                return ResourceManager.GetString("Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TicketNo.
        /// </summary>
        public static string TicketNo {
            get {
                return ResourceManager.GetString("TicketNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Reference No.
        /// </summary>
        public static string TicketReferenceNo {
            get {
                return ResourceManager.GetString("TicketReferenceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToIATACode.
        /// </summary>
        public static string ToIATACode {
            get {
                return ResourceManager.GetString("ToIATACode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Adult Capacity.
        /// </summary>
        public static string TotalAdultCapacity {
            get {
                return ResourceManager.GetString("TotalAdultCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount.
        /// </summary>
        public static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Capacity.
        /// </summary>
        public static string TotalCapacity {
            get {
                return ResourceManager.GetString("TotalCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Child Capacity.
        /// </summary>
        public static string TotalChildCapacity {
            get {
                return ResourceManager.GetString("TotalChildCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total DiscountP rice.
        /// </summary>
        public static string TotalDiscountPrice {
            get {
                return ResourceManager.GetString("TotalDiscountPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Infant Capacity.
        /// </summary>
        public static string TotalInfantCapacity {
            get {
                return ResourceManager.GetString("TotalInfantCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Tax Price.
        /// </summary>
        public static string TotalPayPrice {
            get {
                return ResourceManager.GetString("TotalPayPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price.
        /// </summary>
        public static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Service Price.
        /// </summary>
        public static string TotalServicePrice {
            get {
                return ResourceManager.GetString("TotalServicePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalTaxPrice.
        /// </summary>
        public static string TotalTaxPrice {
            get {
                return ResourceManager.GetString("TotalTaxPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Id.
        /// </summary>
        public static string TourId {
            get {
                return ResourceManager.GetString("TourId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Package Id.
        /// </summary>
        public static string TourPackageId {
            get {
                return ResourceManager.GetString("TourPackageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Package Title.
        /// </summary>
        public static string TourPackageTitle {
            get {
                return ResourceManager.GetString("TourPackageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TourSchedule.
        /// </summary>
        public static string TourSchedule {
            get {
                return ResourceManager.GetString("TourSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Title.
        /// </summary>
        public static string TourTitle {
            get {
                return ResourceManager.GetString("TourTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking Code.
        /// </summary>
        public static string TrackingCode {
            get {
                return ResourceManager.GetString("TrackingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessful.
        /// </summary>
        public static string Unsuccessful {
            get {
                return ResourceManager.GetString("Unsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnSuccessful Payment Logs.
        /// </summary>
        public static string UnSuccessfulPaymentLogs {
            get {
                return ResourceManager.GetString("UnSuccessfulPaymentLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidatedDate.
        /// </summary>
        public static string ValidatedDate {
            get {
                return ResourceManager.GetString("ValidatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidatedUserId.
        /// </summary>
        public static string ValidatedUserId {
            get {
                return ResourceManager.GetString("ValidatedUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
    }
}
