//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParvazPardaz.Resource.General {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Generals {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Generals() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ParvazPardaz.Resource.General.Generals", typeof(Generals).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to remove this?.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Information.
        /// </summary>
        public static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter number digits for country code! (up to 4 d.).
        /// </summary>
        public static string CallCountryPrefixFormat {
            get {
                return ResourceManager.GetString("CallCountryPrefixFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter numer digits for &quot;{0}&quot;!.
        /// </summary>
        public static string CallNumberFormat {
            get {
                return ResourceManager.GetString("CallNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Files.
        /// </summary>
        public static string captionsButton {
            get {
                return ResourceManager.GetString("captionsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop file here to Upload.
        /// </summary>
        public static string captionsDrop {
            get {
                return ResourceManager.GetString("captionsDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only {{fi-limit}} files are allowed to be uploaded..
        /// </summary>
        public static string captionsErFilesLimit {
            get {
                return ResourceManager.GetString("captionsErFilesLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{fi-name}} is too large! Please upload file up to {{fi-fileMaxSize}} MB..
        /// </summary>
        public static string captionsErFilesSize {
            get {
                return ResourceManager.GetString("captionsErFilesSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files you&apos;ve choosed are too large! Please upload files up to {{fi-maxSize}} MB..
        /// </summary>
        public static string captionsErFilesSizeAll {
            get {
                return ResourceManager.GetString("captionsErFilesSizeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Images are allowed to be uploaded..
        /// </summary>
        public static string captionsErFilesType {
            get {
                return ResourceManager.GetString("captionsErFilesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to upload folders..
        /// </summary>
        public static string captionsErFolderUpload {
            get {
                return ResourceManager.GetString("captionsErFolderUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose files To Upload.
        /// </summary>
        public static string captionsFeedback {
            get {
                return ResourceManager.GetString("captionsFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to files were chosen.
        /// </summary>
        public static string captionsFeedback2 {
            get {
                return ResourceManager.GetString("captionsFeedback2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this file?.
        /// </summary>
        public static string captionsRemoveConfirmation {
            get {
                return ResourceManager.GetString("captionsRemoveConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View in Client-side.
        /// </summary>
        public static string ClientSee {
            get {
                return ResourceManager.GetString("ClientSee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        public static string Commands {
            get {
                return ResourceManager.GetString("Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Transfer Management.
        /// </summary>
        public static string CompanyTransferManagement {
            get {
                return ResourceManager.GetString("CompanyTransferManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your information have been confirmed successfully.
        /// </summary>
        public static string ConfirmAlert {
            get {
                return ResourceManager.GetString("ConfirmAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmIt.
        /// </summary>
        public static string ConfirmIt {
            get {
                return ResourceManager.GetString("ConfirmIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string ConfirmTitle {
            get {
                return ResourceManager.GetString("ConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Link.
        /// </summary>
        public static string CopyLink {
            get {
                return ResourceManager.GetString("CopyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to couldNotCascadeDelete.
        /// </summary>
        public static string couldNotCascadeDelete {
            get {
                return ResourceManager.GetString("couldNotCascadeDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your information have been created successfully.
        /// </summary>
        public static string CreateAlert {
            get {
                return ResourceManager.GetString("CreateAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateAlertTitle {
            get {
                return ResourceManager.GetString("CreateAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create and next.
        /// </summary>
        public static string CreateAndNext {
            get {
                return ResourceManager.GetString("CreateAndNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create and repeat.
        /// </summary>
        public static string CreateAndRepeat {
            get {
                return ResourceManager.GetString("CreateAndRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Date Time.
        /// </summary>
        public static string CreatorDateTime {
            get {
                return ResourceManager.GetString("CreatorDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator User.
        /// </summary>
        public static string CreatorUserName {
            get {
                return ResourceManager.GetString("CreatorUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop.
        /// </summary>
        public static string Crop {
            get {
                return ResourceManager.GetString("Crop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croping Result.
        /// </summary>
        public static string CropResult {
            get {
                return ResourceManager.GetString("CropResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select --.
        /// </summary>
        public static string DDLSelect {
            get {
                return ResourceManager.GetString("DDLSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeActive.
        /// </summary>
        public static string DeActive {
            get {
                return ResourceManager.GetString("DeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your information have been removed successfully.
        /// </summary>
        public static string DeleteAlert {
            get {
                return ResourceManager.GetString("DeleteAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string DeleteAlertTitle {
            get {
                return ResourceManager.GetString("DeleteAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LTR.
        /// </summary>
        public static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dislike -.
        /// </summary>
        public static string DisLike {
            get {
                return ResourceManager.GetString("DisLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create dubplicate item..
        /// </summary>
        public static string DuplicateAlert {
            get {
                return ResourceManager.GetString("DuplicateAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dubplicate error!.
        /// </summary>
        public static string DuplicateTitle {
            get {
                return ResourceManager.GetString("DuplicateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your information have been edited successfully.
        /// </summary>
        public static string EditAlert {
            get {
                return ResourceManager.GetString("EditAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditAlertTitle {
            get {
                return ResourceManager.GetString("EditAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorTitle	
        ///	
        ///	
        ///Failure in operation.
        /// </summary>
        public static string ErrorAlert {
            get {
                return ResourceManager.GetString("ErrorAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Try Again !.
        /// </summary>
        public static string ErrorAlertTitle {
            get {
                return ResourceManager.GetString("ErrorAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire Date.
        /// </summary>
        public static string ExpireDate {
            get {
                return ResourceManager.GetString("ExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExportExcel.
        /// </summary>
        public static string ExportExcel {
            get {
                return ResourceManager.GetString("ExportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel.
        /// </summary>
        public static string Hotel {
            get {
                return ResourceManager.GetString("Hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel gallery management.
        /// </summary>
        public static string HotelGalleryManagement {
            get {
                return ResourceManager.GetString("HotelGalleryManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an email address as correct format.
        /// </summary>
        public static string InValidEmail {
            get {
                return ResourceManager.GetString("InValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iranian.
        /// </summary>
        public static string Iranian {
            get {
                return ResourceManager.GetString("Iranian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active ?.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lack Of Credit.
        /// </summary>
        public static string LackOfCredit {
            get {
                return ResourceManager.GetString("LackOfCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modifying Date.
        /// </summary>
        public static string LastModifierDate {
            get {
                return ResourceManager.GetString("LastModifierDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modifier User.
        /// </summary>
        public static string LastModifierUserName {
            get {
                return ResourceManager.GetString("LastModifierUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like +.
        /// </summary>
        public static string Like {
            get {
                return ResourceManager.GetString("Like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Man.
        /// </summary>
        public static string Man {
            get {
                return ResourceManager.GetString("Man", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManagementPermission.
        /// </summary>
        public static string ManagementPermission {
            get {
                return ResourceManager.GetString("ManagementPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter {0} in currect format.
        /// </summary>
        public static string MustBeDecimal {
            get {
                return ResourceManager.GetString("MustBeDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must Be Number.
        /// </summary>
        public static string MustBeNumber {
            get {
                return ResourceManager.GetString("MustBeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Iranian.
        /// </summary>
        public static string NonIranian {
            get {
                return ResourceManager.GetString("NonIranian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not change to update.
        /// </summary>
        public static string NotChangeMessage {
            get {
                return ResourceManager.GetString("NotChangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not have image.
        /// </summary>
        public static string NotHaveImage {
            get {
                return ResourceManager.GetString("NotHaveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office.
        /// </summary>
        public static string Office {
            get {
                return ResourceManager.GetString("Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageName.
        /// </summary>
        public static string PageName {
            get {
                return ResourceManager.GetString("PageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageUrl.
        /// </summary>
        public static string PageUrl {
            get {
                return ResourceManager.GetString("PageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        public static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission for this section.
        /// </summary>
        public static string PermissionAlert {
            get {
                return ResourceManager.GetString("PermissionAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persian.
        /// </summary>
        public static string Persian {
            get {
                return ResourceManager.GetString("Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter mobile number in correct format.
        /// </summary>
        public static string PersianMobileFormat {
            get {
                return ResourceManager.GetString("PersianMobileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PersianPhoneFormat.
        /// </summary>
        public static string PersianPhoneFormat {
            get {
                return ResourceManager.GetString("PersianPhoneFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Log In.
        /// </summary>
        public static string PleaseLogIn {
            get {
                return ResourceManager.GetString("PleaseLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select.
        /// </summary>
        public static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recomended.
        /// </summary>
        public static string Recomended {
            get {
                return ResourceManager.GetString("Recomended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recoverAccess.
        /// </summary>
        public static string recoverAccess {
            get {
                return ResourceManager.GetString("recoverAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EN.
        /// </summary>
        public static string Regional {
            get {
                return ResourceManager.GetString("Regional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select {0}..
        /// </summary>
        public static string RequiredCheckBox {
            get {
                return ResourceManager.GetString("RequiredCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve.
        /// </summary>
        public static string Reserve {
            get {
                return ResourceManager.GetString("Reserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your search content.
        /// </summary>
        public static string SearchContentRequiredAlert {
            get {
                return ResourceManager.GetString("SearchContentRequiredAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchParameters.
        /// </summary>
        public static string SearchParameters {
            get {
                return ResourceManager.GetString("SearchParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select one row.
        /// </summary>
        public static string SelectedGridRowAlert {
            get {
                return ResourceManager.GetString("SelectedGridRowAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SelectedGridRowAlertTitle {
            get {
                return ResourceManager.GetString("SelectedGridRowAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select image.
        /// </summary>
        public static string SelectImage {
            get {
                return ResourceManager.GetString("SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabet.
        /// </summary>
        public static string SortByAlphabet {
            get {
                return ResourceManager.GetString("SortByAlphabet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum hotel rank.
        /// </summary>
        public static string SortByMostHotelRank {
            get {
                return ResourceManager.GetString("SortByMostHotelRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum like.
        /// </summary>
        public static string SortByMostLike {
            get {
                return ResourceManager.GetString("SortByMostLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum rate.
        /// </summary>
        public static string SortByMostRate {
            get {
                return ResourceManager.GetString("SortByMostRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum review count.
        /// </summary>
        public static string SortByReviewCount {
            get {
                return ResourceManager.GetString("SortByReviewCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting by.
        /// </summary>
        public static string SortingBy {
            get {
                return ResourceManager.GetString("SortingBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms And Conditions.
        /// </summary>
        public static string TermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour.
        /// </summary>
        public static string Tour {
            get {
                return ResourceManager.GetString("Tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again!.
        /// </summary>
        public static string TryAginMessage {
            get {
                return ResourceManager.GetString("TryAginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-side management.
        /// </summary>
        public static string UserSideManagement {
            get {
                return ResourceManager.GetString("UserSideManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Site Management.
        /// </summary>
        public static string WebSiteManagement {
            get {
                return ResourceManager.GetString("WebSiteManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keysafar user panel.
        /// </summary>
        public static string WebSiteUserPanel {
            get {
                return ResourceManager.GetString("WebSiteUserPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woman.
        /// </summary>
        public static string Woman {
            get {
                return ResourceManager.GetString("Woman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter currect old password.
        /// </summary>
        public static string WrongOldPassword {
            get {
                return ResourceManager.GetString("WrongOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Password Reseted.
        /// </summary>
        public static string YourPasswordReseted {
            get {
                return ResourceManager.GetString("YourPasswordReseted", resourceCulture);
            }
        }
    }
}
