//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParvazPardaz.Resource.EShop {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EShopResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EShopResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ParvazPardaz.Resource.EShop.EShopResource", typeof(EShopResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccessLevel.
        /// </summary>
        public static string AccessLevel {
            get {
                return ResourceManager.GetString("AccessLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Attribute.
        /// </summary>
        public static string addAttribute {
            get {
                return ResourceManager.GetString("addAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Post.
        /// </summary>
        public static string AddPost {
            get {
                return ResourceManager.GetString("AddPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddProduct.
        /// </summary>
        public static string AddProduct {
            get {
                return ResourceManager.GetString("AddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admins.
        /// </summary>
        public static string admins {
            get {
                return ResourceManager.GetString("admins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        public static string Attribute {
            get {
                return ResourceManager.GetString("Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Management.
        /// </summary>
        public static string AttributeManagment {
            get {
                return ResourceManager.GetString("AttributeManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Value Management.
        /// </summary>
        public static string AttributeValueManagement {
            get {
                return ResourceManager.GetString("AttributeValueManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner Group.
        /// </summary>
        public static string BannerGroup {
            get {
                return ResourceManager.GetString("BannerGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        public static string Barcode {
            get {
                return ResourceManager.GetString("Barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CancelationPolicy.
        /// </summary>
        public static string CancelationPolicy {
            get {
                return ResourceManager.GetString("CancelationPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Product Default Image.
        /// </summary>
        public static string ChangeDefaultProductThumb {
            get {
                return ResourceManager.GetString("ChangeDefaultProductThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges.
        /// </summary>
        public static string Charges {
            get {
                return ResourceManager.GetString("Charges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckOutDateTime.
        /// </summary>
        public static string CheckOutDateTime {
            get {
                return ResourceManager.GetString("CheckOutDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommentText.
        /// </summary>
        public static string CommentText {
            get {
                return ResourceManager.GetString("CommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment for.
        /// </summary>
        public static string CommentType {
            get {
                return ResourceManager.GetString("CommentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyName.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        public static string CreateAttributeId {
            get {
                return ResourceManager.GetString("CreateAttributeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute value.
        /// </summary>
        public static string CreateAttValueId {
            get {
                return ResourceManager.GetString("CreateAttValueId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string CreatePriority {
            get {
                return ResourceManager.GetString("CreatePriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomans.
        /// </summary>
        public static string CurrencyRials {
            get {
                return ResourceManager.GetString("CurrencyRials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered.
        /// </summary>
        public static string Delivered {
            get {
                return ResourceManager.GetString("Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DiscountAmount.
        /// </summary>
        public static string DiscountAmount {
            get {
                return ResourceManager.GetString("DiscountAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DiscountFullName.
        /// </summary>
        public static string DiscountFullName {
            get {
                return ResourceManager.GetString("DiscountFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display On Home Page.
        /// </summary>
        public static string DisplayOnHomePage {
            get {
                return ResourceManager.GetString("DisplayOnHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnglishTitle.
        /// </summary>
        public static string EnglishTitle {
            get {
                return ResourceManager.GetString("EnglishTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire Datetime.
        /// </summary>
        public static string ExpireDatetime {
            get {
                return ResourceManager.GetString("ExpireDatetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor.
        /// </summary>
        public static string Factor {
            get {
                return ResourceManager.GetString("Factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstBanner.
        /// </summary>
        public static string FirstBanner {
            get {
                return ResourceManager.GetString("FirstBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FourthBanner.
        /// </summary>
        public static string FourthBanner {
            get {
                return ResourceManager.GetString("FourthBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to general.
        /// </summary>
        public static string general {
            get {
                return ResourceManager.GetString("general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string HotelGroup {
            get {
                return ResourceManager.GetString("HotelGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management of Hotel Group.
        /// </summary>
        public static string HotelGroupManagement {
            get {
                return ResourceManager.GetString("HotelGroupManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HotelRank.
        /// </summary>
        public static string HotelRank {
            get {
                return ResourceManager.GetString("HotelRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Rate.
        /// </summary>
        public static string HotelRate {
            get {
                return ResourceManager.GetString("HotelRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HotelRule.
        /// </summary>
        public static string HotelRule {
            get {
                return ResourceManager.GetString("HotelRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InPlace.
        /// </summary>
        public static string InPlace {
            get {
                return ResourceManager.GetString("InPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsActive ?.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsActiveComments.
        /// </summary>
        public static string IsActiveComments {
            get {
                return ResourceManager.GetString("IsActiveComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsApproved.
        /// </summary>
        public static string IsApproved {
            get {
                return ResourceManager.GetString("IsApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to link.
        /// </summary>
        public static string link {
            get {
                return ResourceManager.GetString("link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Of Banners.
        /// </summary>
        public static string ManagementBanner {
            get {
                return ResourceManager.GetString("ManagementBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management of Banners.
        /// </summary>
        public static string ManagementBanners {
            get {
                return ResourceManager.GetString("ManagementBanners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management of Brands.
        /// </summary>
        public static string ManagementBrands {
            get {
                return ResourceManager.GetString("ManagementBrands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mnagement of Users Comments.
        /// </summary>
        public static string ManagementComments {
            get {
                return ResourceManager.GetString("ManagementComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Of Packages.
        /// </summary>
        public static string ManagementPackage {
            get {
                return ResourceManager.GetString("ManagementPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Of Package&apos;s Products.
        /// </summary>
        public static string ManagementPackageProducts {
            get {
                return ResourceManager.GetString("ManagementPackageProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management of product comments.
        /// </summary>
        public static string ManagementProductComments {
            get {
                return ResourceManager.GetString("ManagementProductComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management of product default thumbnail image.
        /// </summary>
        public static string ManagementProductDefaultThumbImage {
            get {
                return ResourceManager.GetString("ManagementProductDefaultThumbImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management of Products.
        /// </summary>
        public static string ManagementProducts {
            get {
                return ResourceManager.GetString("ManagementProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Of Product Types.
        /// </summary>
        public static string ManagementProductType {
            get {
                return ResourceManager.GetString("ManagementProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to members.
        /// </summary>
        public static string members {
            get {
                return ResourceManager.GetString("members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuBlockType.
        /// </summary>
        public static string MenuBlockType {
            get {
                return ResourceManager.GetString("MenuBlockType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuBrandType.
        /// </summary>
        public static string MenuBrandType {
            get {
                return ResourceManager.GetString("MenuBrandType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cascading Type.
        /// </summary>
        public static string MenuCascadingType {
            get {
                return ResourceManager.GetString("MenuCascadingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuLinkType.
        /// </summary>
        public static string MenuLinkType {
            get {
                return ResourceManager.GetString("MenuLinkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuNothingType.
        /// </summary>
        public static string MenuNothingType {
            get {
                return ResourceManager.GetString("MenuNothingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuPageType.
        /// </summary>
        public static string MenuPageType {
            get {
                return ResourceManager.GetString("MenuPageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuSpecialLinkOnLeftType.
        /// </summary>
        public static string MenuSpecialLinkOnLeftType {
            get {
                return ResourceManager.GetString("MenuSpecialLinkOnLeftType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetaDescription.
        /// </summary>
        public static string MetaDescription {
            get {
                return ResourceManager.GetString("MetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetaKeywords.
        /// </summary>
        public static string MetaKeywords {
            get {
                return ResourceManager.GetString("MetaKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MobileNumber.
        /// </summary>
        public static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to motorcycleDelivery.
        /// </summary>
        public static string motorcycleDelivery {
            get {
                return ResourceManager.GetString("motorcycleDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewOrder.
        /// </summary>
        public static string NewOrder {
            get {
                return ResourceManager.GetString("NewOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderCode.
        /// </summary>
        public static string OrderCode {
            get {
                return ResourceManager.GetString("OrderCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderDescription.
        /// </summary>
        public static string OrderDescription {
            get {
                return ResourceManager.GetString("OrderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderId.
        /// </summary>
        public static string OrderId {
            get {
                return ResourceManager.GetString("OrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderState.
        /// </summary>
        public static string OrderState {
            get {
                return ResourceManager.GetString("OrderState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderTitle.
        /// </summary>
        public static string OrderTitle {
            get {
                return ResourceManager.GetString("OrderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderTrackingCode.
        /// </summary>
        public static string OrderTrackingCode {
            get {
                return ResourceManager.GetString("OrderTrackingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Link.
        /// </summary>
        public static string OwnLink {
            get {
                return ResourceManager.GetString("OwnLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string OwnTitle {
            get {
                return ResourceManager.GetString("OwnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package.
        /// </summary>
        public static string Package {
            get {
                return ResourceManager.GetString("Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Name.
        /// </summary>
        public static string PackageName {
            get {
                return ResourceManager.GetString("PackageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing.
        /// </summary>
        public static string Packing {
            get {
                return ResourceManager.GetString("Packing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        public static string Parent {
            get {
                return ResourceManager.GetString("Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management of PaymentLog.
        /// </summary>
        public static string PaymentLogManagement {
            get {
                return ResourceManager.GetString("PaymentLogManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful PaymentLog.
        /// </summary>
        public static string PaymentLogSuccessful {
            get {
                return ResourceManager.GetString("PaymentLogSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnSuccessful PaymentLog.
        /// </summary>
        public static string PaymentLogUnSuccessful {
            get {
                return ResourceManager.GetString("PaymentLogUnSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentType.
        /// </summary>
        public static string PaymentType {
            get {
                return ResourceManager.GetString("PaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentType.
        /// </summary>
        public static string PaymentTypeId {
            get {
                return ResourceManager.GetString("PaymentTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pending.
        /// </summary>
        public static string pending {
            get {
                return ResourceManager.GetString("pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PictureCount.
        /// </summary>
        public static string PictureCount {
            get {
                return ResourceManager.GetString("PictureCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Comment.
        /// </summary>
        public static string PostComment {
            get {
                return ResourceManager.GetString("PostComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostContent.
        /// </summary>
        public static string PostContent {
            get {
                return ResourceManager.GetString("PostContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostGroup.
        /// </summary>
        public static string PostGroup {
            get {
                return ResourceManager.GetString("PostGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostGroupManagement.
        /// </summary>
        public static string PostGroupManagement {
            get {
                return ResourceManager.GetString("PostGroupManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to postImage.
        /// </summary>
        public static string postImage {
            get {
                return ResourceManager.GetString("postImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostManagement.
        /// </summary>
        public static string PostManagement {
            get {
                return ResourceManager.GetString("PostManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Rate Avg.
        /// </summary>
        public static string PostRateAvg {
            get {
                return ResourceManager.GetString("PostRateAvg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostRateCount.
        /// </summary>
        public static string PostRateCount {
            get {
                return ResourceManager.GetString("PostRateCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostSummery.
        /// </summary>
        public static string PostSummery {
            get {
                return ResourceManager.GetString("PostSummery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to preFactor.
        /// </summary>
        public static string preFactor {
            get {
                return ResourceManager.GetString("preFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price In Package.
        /// </summary>
        public static string PriceInPackage {
            get {
                return ResourceManager.GetString("PriceInPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PriceWithDiscount.
        /// </summary>
        public static string PriceWithDiscount {
            get {
                return ResourceManager.GetString("PriceWithDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Attributes.
        /// </summary>
        public static string ProductAttributes {
            get {
                return ResourceManager.GetString("ProductAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Base Informations.
        /// </summary>
        public static string ProductBaseInfos {
            get {
                return ResourceManager.GetString("ProductBaseInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductCode.
        /// </summary>
        public static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Comment.
        /// </summary>
        public static string ProductComment {
            get {
                return ResourceManager.GetString("ProductComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductCount.
        /// </summary>
        public static string ProductCount {
            get {
                return ResourceManager.GetString("ProductCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductDescription.
        /// </summary>
        public static string ProductDescription {
            get {
                return ResourceManager.GetString("ProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductPrice.
        /// </summary>
        public static string ProductPrice {
            get {
                return ResourceManager.GetString("ProductPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Tags.
        /// </summary>
        public static string ProductTags {
            get {
                return ResourceManager.GetString("ProductTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductType.
        /// </summary>
        public static string ProductType {
            get {
                return ResourceManager.GetString("ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PublishDatetime.
        /// </summary>
        public static string PublishDatetime {
            get {
                return ResourceManager.GetString("PublishDatetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RateCount.
        /// </summary>
        public static string RateCount {
            get {
                return ResourceManager.GetString("RateCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchTitle.
        /// </summary>
        public static string SearchTitle {
            get {
                return ResourceManager.GetString("SearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecondBanner.
        /// </summary>
        public static string SecondBanner {
            get {
                return ResourceManager.GetString("SecondBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select images.
        /// </summary>
        public static string SelectMultipleImg {
            get {
                return ResourceManager.GetString("SelectMultipleImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sellManagement.
        /// </summary>
        public static string sellManagement {
            get {
                return ResourceManager.GetString("sellManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sended.
        /// </summary>
        public static string Sended {
            get {
                return ResourceManager.GetString("Sended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShippingType.
        /// </summary>
        public static string ShippingType {
            get {
                return ResourceManager.GetString("ShippingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShippingType.
        /// </summary>
        public static string ShippingTypeId {
            get {
                return ResourceManager.GetString("ShippingTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Order.
        /// </summary>
        public static string SortOrder {
            get {
                return ResourceManager.GetString("SortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose.
        /// </summary>
        public static string submenu {
            get {
                return ResourceManager.GetString("submenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to submenuAndImage.
        /// </summary>
        public static string submenuAndImage {
            get {
                return ResourceManager.GetString("submenuAndImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to submenuAndRootImage.
        /// </summary>
        public static string submenuAndRootImage {
            get {
                return ResourceManager.GetString("submenuAndRootImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Group.
        /// </summary>
        public static string TabGroup {
            get {
                return ResourceManager.GetString("TabGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Group Managment.
        /// </summary>
        public static string TabGroupManagment {
            get {
                return ResourceManager.GetString("TabGroupManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tabProduct.
        /// </summary>
        public static string tabProduct {
            get {
                return ResourceManager.GetString("tabProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Product Management.
        /// </summary>
        public static string TabProductManagement {
            get {
                return ResourceManager.GetString("TabProductManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Product Managment.
        /// </summary>
        public static string TabProductManagment {
            get {
                return ResourceManager.GetString("TabProductManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        public static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel.
        /// </summary>
        public static string Tel {
            get {
                return ResourceManager.GetString("Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TermsAndConditions.
        /// </summary>
        public static string TermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThirdBanner.
        /// </summary>
        public static string ThirdBanner {
            get {
                return ResourceManager.GetString("ThirdBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail.
        /// </summary>
        public static string Thumbnail {
            get {
                return ResourceManager.GetString("Thumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToAccount.
        /// </summary>
        public static string ToAccount {
            get {
                return ResourceManager.GetString("ToAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToCart.
        /// </summary>
        public static string ToCart {
            get {
                return ResourceManager.GetString("ToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalDiscount.
        /// </summary>
        public static string TotalDiscount {
            get {
                return ResourceManager.GetString("TotalDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalPay.
        /// </summary>
        public static string TotalPay {
            get {
                return ResourceManager.GetString("TotalPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalPrice.
        /// </summary>
        public static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking.
        /// </summary>
        public static string Tracking {
            get {
                return ResourceManager.GetString("Tracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tracking Code.
        /// </summary>
        public static string trackingCode {
            get {
                return ResourceManager.GetString("trackingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking Order.
        /// </summary>
        public static string TrackingOrder {
            get {
                return ResourceManager.GetString("TrackingOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vipusers.
        /// </summary>
        public static string vipusers {
            get {
                return ResourceManager.GetString("vipusers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisitCount.
        /// </summary>
        public static string VisitCount {
            get {
                return ResourceManager.GetString("VisitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writer.
        /// </summary>
        public static string Writer {
            get {
                return ResourceManager.GetString("Writer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZipCode.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
