//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParvazPardaz.Resource.CMS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CMS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CMS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ParvazPardaz.Resource.CMS.CMS", typeof(CMS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Contact.
        /// </summary>
        public static string AddContact {
            get {
                return ResourceManager.GetString("AddContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddContactItem.
        /// </summary>
        public static string AddContactItem {
            get {
                return ResourceManager.GetString("AddContactItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Default Column.
        /// </summary>
        public static string AddDefaultColumn {
            get {
                return ResourceManager.GetString("AddDefaultColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddEmail.
        /// </summary>
        public static string AddEmail {
            get {
                return ResourceManager.GetString("AddEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddFacebook.
        /// </summary>
        public static string AddFacebook {
            get {
                return ResourceManager.GetString("AddFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddFax.
        /// </summary>
        public static string AddFax {
            get {
                return ResourceManager.GetString("AddFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Footer.
        /// </summary>
        public static string AddFooter {
            get {
                return ResourceManager.GetString("AddFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddGooglePlus.
        /// </summary>
        public static string AddGooglePlus {
            get {
                return ResourceManager.GetString("AddGooglePlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddInstagram.
        /// </summary>
        public static string AddInstagram {
            get {
                return ResourceManager.GetString("AddInstagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Menu Group.
        /// </summary>
        public static string AddMenuGroup {
            get {
                return ResourceManager.GetString("AddMenuGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddMobile.
        /// </summary>
        public static string AddMobile {
            get {
                return ResourceManager.GetString("AddMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Newsletter.
        /// </summary>
        public static string AddNewsletter {
            get {
                return ResourceManager.GetString("AddNewsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Page.
        /// </summary>
        public static string AddPage {
            get {
                return ResourceManager.GetString("AddPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Social Network Item.
        /// </summary>
        public static string AddSocialItem {
            get {
                return ResourceManager.GetString("AddSocialItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Subfooter .
        /// </summary>
        public static string AddSubFooter {
            get {
                return ResourceManager.GetString("AddSubFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Supporting report.
        /// </summary>
        public static string AddSupport {
            get {
                return ResourceManager.GetString("AddSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddTel.
        /// </summary>
        public static string AddTel {
            get {
                return ResourceManager.GetString("AddTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Title.
        /// </summary>
        public static string AddTitle {
            get {
                return ResourceManager.GetString("AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddTwitter.
        /// </summary>
        public static string AddTwitter {
            get {
                return ResourceManager.GetString("AddTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog Footer.
        /// </summary>
        public static string BlogFooter {
            get {
                return ResourceManager.GetString("BlogFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientPage.
        /// </summary>
        public static string ClientPage {
            get {
                return ResourceManager.GetString("ClientPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Code.
        /// </summary>
        public static string ColorCode {
            get {
                return ResourceManager.GetString("ColorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        public static string Commands {
            get {
                return ResourceManager.GetString("Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment Is Active ?.
        /// </summary>
        public static string CommentIsActive {
            get {
                return ResourceManager.GetString("CommentIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact groups.
        /// </summary>
        public static string ContactGroupIdList {
            get {
                return ResourceManager.GetString("ContactGroupIdList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Group.
        /// </summary>
        public static string ContentGroup {
            get {
                return ResourceManager.GetString("ContentGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context.
        /// </summary>
        public static string Context {
            get {
                return ResourceManager.GetString("Context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Link.
        /// </summary>
        public static string CopyLink {
            get {
                return ResourceManager.GetString("CopyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;&lt;div class=&quot;links&quot;&gt;&apos; +
        ///	&apos;&lt;ul&gt;&apos; +
        ///		&apos;&lt;li class=&quot;mobile&quot;&gt;&lt;i class=&quot;fa fa-phone&quot;&gt;&lt;/i&gt;+21 9898777656&lt;/li&gt;&apos; +
        ///		&apos;&lt;li class=&quot;email&quot;&gt;&lt;a href=&quot;#&quot;&gt;&lt;i class=&quot;fa fa-envelope&quot;&gt;&lt;/i&gt;info@sorrad.com&lt;/a&gt;&lt;/li&gt;&apos; +
        ///		&apos;&lt;li class=&quot;wrap_custom_block hidden-sm hidden-xs&quot;&gt;&apos; +
        ///			&apos;&lt;a&gt;بلاک سفارشی&lt;b&gt;&lt;/b&gt;&lt;/a&gt;&apos; +
        ///			&apos;&lt;div class=&quot;dropdown-menu custom_block&quot; style=&quot;display: none;&quot;&gt;&apos; +
        ///				&apos;&lt;ul&gt;&apos; +
        ///					&apos;&lt;li&gt;&apos; +
        ///						&apos;&lt;table&gt;&apos; +
        ///							&apos;&lt;tbody&gt;&apos; +
        ///								&apos;&lt;tr&gt;&apos; +
        ///									&apos;&lt;td&gt;&lt;img alt=&quot;&quot; src=&quot;/ClientTheme/image/banner/cms- [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DefaultStyle {
            get {
                return ResourceManager.GetString("DefaultStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Style.
        /// </summary>
        public static string DefaultStyleTitle {
            get {
                return ResourceManager.GetString("DefaultStyleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Contact.
        /// </summary>
        public static string DeleteContact {
            get {
                return ResourceManager.GetString("DeleteContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Contact.
        /// </summary>
        public static string EditContact {
            get {
                return ResourceManager.GetString("EditContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error On Delete.
        /// </summary>
        public static string ErrorInDelete {
            get {
                return ResourceManager.GetString("ErrorInDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expirationdate.
        /// </summary>
        public static string Expirationdate {
            get {
                return ResourceManager.GetString("Expirationdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Level?.
        /// </summary>
        public static string FirstLevel {
            get {
                return ResourceManager.GetString("FirstLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer.
        /// </summary>
        public static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to footerLine1.
        /// </summary>
        public static string footerLine1 {
            get {
                return ResourceManager.GetString("footerLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to footerLine2.
        /// </summary>
        public static string footerLine2 {
            get {
                return ResourceManager.GetString("footerLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer Management.
        /// </summary>
        public static string FooterManagement {
            get {
                return ResourceManager.GetString("FooterManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer Type.
        /// </summary>
        public static string FooterType {
            get {
                return ResourceManager.GetString("FooterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HeaderDays.
        /// </summary>
        public static string HeaderDays {
            get {
                return ResourceManager.GetString("HeaderDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Tab Magazine.
        /// </summary>
        public static string HomeTabMagazine {
            get {
                return ResourceManager.GetString("HomeTabMagazine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image URL.
        /// </summary>
        public static string ImageURL {
            get {
                return ResourceManager.GetString("ImageURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active ?.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Comment Active ?.
        /// </summary>
        public static string IsCommentActive {
            get {
                return ResourceManager.GetString("IsCommentActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Root?.
        /// </summary>
        public static string IsRoot {
            get {
                return ResourceManager.GetString("IsRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JobTitle.
        /// </summary>
        public static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string LinkTitle {
            get {
                return ResourceManager.GetString("LinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Footer.
        /// </summary>
        public static string MainFooter {
            get {
                return ResourceManager.GetString("MainFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact groups management.
        /// </summary>
        public static string ManagementContactGroups {
            get {
                return ResourceManager.GetString("ManagementContactGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts management.
        /// </summary>
        public static string ManagementContacts {
            get {
                return ResourceManager.GetString("ManagementContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts management  for .
        /// </summary>
        public static string ManagementContactsForUser {
            get {
                return ResourceManager.GetString("ManagementContactsForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Of Contact Us.
        /// </summary>
        public static string ManagementContactUs {
            get {
                return ResourceManager.GetString("ManagementContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Of Content Groups.
        /// </summary>
        public static string ManagementContentGroups {
            get {
                return ResourceManager.GetString("ManagementContentGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Of Department.
        /// </summary>
        public static string ManagementDepartment {
            get {
                return ResourceManager.GetString("ManagementDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer Management.
        /// </summary>
        public static string ManagementFooter {
            get {
                return ResourceManager.GetString("ManagementFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet address types management.
        /// </summary>
        public static string ManagementInternetAddressTypes {
            get {
                return ResourceManager.GetString("ManagementInternetAddressTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Of Last Second Tours.
        /// </summary>
        public static string ManagementLastSecondTours {
            get {
                return ResourceManager.GetString("ManagementLastSecondTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management of  Link Redirection 301.
        /// </summary>
        public static string ManagementLinkRedirection {
            get {
                return ResourceManager.GetString("ManagementLinkRedirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Of Tab Landing Page&apos;s Locations.
        /// </summary>
        public static string ManagementLocations {
            get {
                return ResourceManager.GetString("ManagementLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Management.
        /// </summary>
        public static string ManagementMenu {
            get {
                return ResourceManager.GetString("ManagementMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Group Management.
        /// </summary>
        public static string ManagementMenuGroup {
            get {
                return ResourceManager.GetString("ManagementMenuGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewsLetter Management.
        /// </summary>
        public static string ManagementNewsLetter {
            get {
                return ResourceManager.GetString("ManagementNewsLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Management.
        /// </summary>
        public static string ManagementPages {
            get {
                return ResourceManager.GetString("ManagementPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Of Permissions.
        /// </summary>
        public static string ManagementPermission {
            get {
                return ResourceManager.GetString("ManagementPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone types management.
        /// </summary>
        public static string ManagementPhoneTypes {
            get {
                return ResourceManager.GetString("ManagementPhoneTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal address type management.
        /// </summary>
        public static string ManagementPostalAddressType {
            get {
                return ResourceManager.GetString("ManagementPostalAddressType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Of Review Items.
        /// </summary>
        public static string ManagementReviewItems {
            get {
                return ResourceManager.GetString("ManagementReviewItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider Management.
        /// </summary>
        public static string ManagementSlider {
            get {
                return ResourceManager.GetString("ManagementSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider Group Management.
        /// </summary>
        public static string ManagementSliderGroup {
            get {
                return ResourceManager.GetString("ManagementSliderGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManagementSliderHome.
        /// </summary>
        public static string ManagementSliderHome {
            get {
                return ResourceManager.GetString("ManagementSliderHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManagementSliderTourLanding.
        /// </summary>
        public static string ManagementSliderTourLanding {
            get {
                return ResourceManager.GetString("ManagementSliderTourLanding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Of Support.
        /// </summary>
        public static string ManagementSupport {
            get {
                return ResourceManager.GetString("ManagementSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management of Tab Magazine.
        /// </summary>
        public static string ManagementTabMagazine {
            get {
                return ResourceManager.GetString("ManagementTabMagazine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Of Tour Landing Page&apos;s Urls.
        /// </summary>
        public static string ManagementTourLandingPageUrls {
            get {
                return ResourceManager.GetString("ManagementTourLandingPageUrls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Manager.
        /// </summary>
        public static string ManagerName {
            get {
                return ResourceManager.GetString("ManagerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Group.
        /// </summary>
        public static string MenuGroup {
            get {
                return ResourceManager.GetString("MenuGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Group.
        /// </summary>
        public static string MenuGroupId {
            get {
                return ResourceManager.GetString("MenuGroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active ?.
        /// </summary>
        public static string MenuIsActive {
            get {
                return ResourceManager.GetString("MenuIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Parent.
        /// </summary>
        public static string MenuParentId {
            get {
                return ResourceManager.GetString("MenuParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Title.
        /// </summary>
        public static string MenuTitle {
            get {
                return ResourceManager.GetString("MenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Type.
        /// </summary>
        public static string MenuType {
            get {
                return ResourceManager.GetString("MenuType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string MenuUrl {
            get {
                return ResourceManager.GetString("MenuUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NavDescription.
        /// </summary>
        public static string NavDescription {
            get {
                return ResourceManager.GetString("NavDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation Url.
        /// </summary>
        public static string NavigationUrl {
            get {
                return ResourceManager.GetString("NavigationUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Link.
        /// </summary>
        public static string NewLink {
            get {
                return ResourceManager.GetString("NewLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsletter.
        /// </summary>
        public static string Newsletter {
            get {
                return ResourceManager.GetString("Newsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsletter Management.
        /// </summary>
        public static string NewsletterManagement {
            get {
                return ResourceManager.GetString("NewsletterManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Link.
        /// </summary>
        public static string OldLink {
            get {
                return ResourceManager.GetString("OldLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string OrderId {
            get {
                return ResourceManager.GetString("OrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Content.
        /// </summary>
        public static string PageContent {
            get {
                return ResourceManager.GetString("PageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string PageDatetime {
            get {
                return ResourceManager.GetString("PageDatetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string PageDesc {
            get {
                return ResourceManager.GetString("PageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Image.
        /// </summary>
        public static string PageHeaderImg {
            get {
                return ResourceManager.GetString("PageHeaderImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Management.
        /// </summary>
        public static string PageManagement {
            get {
                return ResourceManager.GetString("PageManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Tags.
        /// </summary>
        public static string PageMetaTags {
            get {
                return ResourceManager.GetString("PageMetaTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Name.
        /// </summary>
        public static string PageName {
            get {
                return ResourceManager.GetString("PageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Title.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        public static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        public static string PermissionId {
            get {
                return ResourceManager.GetString("PermissionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PermissionName.
        /// </summary>
        public static string PermissionName {
            get {
                return ResourceManager.GetString("PermissionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Blog first page slider picture size must be 1280*800 px.
        /// </summary>
        public static string PicSizeBlogFisrtPageSlider {
            get {
                return ResourceManager.GetString("PicSizeBlogFisrtPageSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for slider box , picture must be in 370*310 px.
        /// </summary>
        public static string PicSizeFisrtPageCountryBox {
            get {
                return ResourceManager.GetString("PicSizeFisrtPageCountryBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for nowruz slide box , picture must be in 740*310 px.
        /// </summary>
        public static string PicSizeFisrtPageNowruzBoxSlide {
            get {
                return ResourceManager.GetString("PicSizeFisrtPageNowruzBoxSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for first page slider , picture must be in 1280*573 px.
        /// </summary>
        public static string PicSizeFisrtPageSlider {
            get {
                return ResourceManager.GetString("PicSizeFisrtPageSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for first page discount tour slider , picture must be in 447*342 px.
        /// </summary>
        public static string PicSizeFisrtPageTourSlider {
            get {
                return ResourceManager.GetString("PicSizeFisrtPageTourSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PicSizeTourSuggestion.
        /// </summary>
        public static string PicSizeTourSuggestion {
            get {
                return ResourceManager.GetString("PicSizeTourSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select &quot;PanelUser&quot; Role.
        /// </summary>
        public static string PleaseSelectPanelUserRole {
            get {
                return ResourceManager.GetString("PleaseSelectPanelUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Type.
        /// </summary>
        public static string PostType {
            get {
                return ResourceManager.GetString("PostType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For.
        /// </summary>
        public static string ReviewType {
            get {
                return ResourceManager.GetString("ReviewType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Successfully.
        /// </summary>
        public static string SaveSuccessful {
            get {
                return ResourceManager.GetString("SaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string SelectedGroups {
            get {
                return ResourceManager.GetString("SelectedGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string SelectedTags {
            get {
                return ResourceManager.GetString("SelectedTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select roles.
        /// </summary>
        public static string selectRoles {
            get {
                return ResourceManager.GetString("selectRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping Rules.
        /// </summary>
        public static string ShoppingRules {
            get {
                return ResourceManager.GetString("ShoppingRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Description.
        /// </summary>
        public static string ShortDescription {
            get {
                return ResourceManager.GetString("ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider Group.
        /// </summary>
        public static string SliderGroupID {
            get {
                return ResourceManager.GetString("SliderGroupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SliderGroupTitle.
        /// </summary>
        public static string SliderGroupTitle {
            get {
                return ResourceManager.GetString("SliderGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subfooter.
        /// </summary>
        public static string SubFooter {
            get {
                return ResourceManager.GetString("SubFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Date.
        /// </summary>
        public static string SupportDateTime {
            get {
                return ResourceManager.GetString("SupportDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TagManagement.
        /// </summary>
        public static string TagManagement {
            get {
                return ResourceManager.GetString("TagManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in other page.
        /// </summary>
        public static string TargetBlank {
            get {
                return ResourceManager.GetString("TargetBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open on this page.
        /// </summary>
        public static string TargetSelf {
            get {
                return ResourceManager.GetString("TargetSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms And Conditions.
        /// </summary>
        public static string TermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TermsAndConditionsManagement.
        /// </summary>
        public static string TermsAndConditionsManagement {
            get {
                return ResourceManager.GetString("TermsAndConditionsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket.
        /// </summary>
        public static string Ticket {
            get {
                return ResourceManager.GetString("Ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title (EN).
        /// </summary>
        public static string TitleEN {
            get {
                return ResourceManager.GetString("TitleEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title (FA).
        /// </summary>
        public static string TitleFA {
            get {
                return ResourceManager.GetString("TitleFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Type_0 {
            get {
                return ResourceManager.GetString("Type_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main menu link | submenus links.
        /// </summary>
        public static string Type_1 {
            get {
                return ResourceManager.GetString("Type_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submenus + submenu&apos;s picture.
        /// </summary>
        public static string Type_2 {
            get {
                return ResourceManager.GetString("Type_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submenus + main menu&apos;s picture.
        /// </summary>
        public static string Type_3 {
            get {
                return ResourceManager.GetString("Type_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical description.
        /// </summary>
        public static string UpdateAdminDescription {
            get {
                return ResourceManager.GetString("UpdateAdminDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string UpdateDescription {
            get {
                return ResourceManager.GetString("UpdateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete it?.
        /// </summary>
        public static string WantDelete {
            get {
                return ResourceManager.GetString("WantDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add correct data.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
