//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParvazPardaz.Payment.Infrastructure.Resource
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BankResource
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BankResource()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ParvazPardaz.Payment.Infrastructure.Resource.BankResource", typeof(BankResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to رمز کارت 3 مرتبه اشتباه وارد شده است و در نتیجه کارت غیر فعال خواهد شد.
        /// </summary>
        public static string AllowablePINTriesExceededPickUp
        {
            get
            {
                return ResourceManager.GetString("AllowablePINTriesExceededPickUp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to کاربر انصراف داده است.
        /// </summary>
        public static string CanceledByUser
        {
            get
            {
                return ResourceManager.GetString("CanceledByUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to مبلغ بیش از سقف برداشت می باشد.
        /// </summary>
        public static string ExceedsWithdrawalAmountLimit
        {
            get
            {
                return ResourceManager.GetString("ExceedsWithdrawalAmountLimit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to از تاریخ انقضای کارت گذشته است و کارت دیگر معتبر نیست.
        /// </summary>
        public static string ExpiredCardPickUp
        {
            get
            {
                return ResourceManager.GetString("ExpiredCardPickUp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to پرداخت انجام نشد.
        /// </summary>
        public static string Failed
        {
            get
            {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to خریدار رمز کارت را اشتباه وارد کرده است.
        /// </summary>
        public static string IncorrectPIN
        {
            get
            {
                return ResourceManager.GetString("IncorrectPIN", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to مبلغ سند برگشتی، از مبلغ تراکنش اصلی بیشتر است.
        /// </summary>
        public static string InvalidAmount
        {
            get
            {
                return ResourceManager.GetString("InvalidAmount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to شماره کارت اشتباه است.
        /// </summary>
        public static string InvalidCardNumber
        {
            get
            {
                return ResourceManager.GetString("InvalidCardNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to پارامترهای ارسالی نامعتبر است.
        /// </summary>
        public static string InvalidParameters
        {
            get
            {
                return ResourceManager.GetString("InvalidParameters", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to درخواست برگشت یک تراکنش رسیده است ، درحالی که تراکنش اصلی پیدا نمی شود.
        /// </summary>
        public static string InvalidTransaction
        {
            get
            {
                return ResourceManager.GetString("InvalidTransaction", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to سیستم بانک صادر کننده کارت خریدار، در وضعیت عملیاتی نیست.
        /// </summary>
        public static string IssuerDownSlm
        {
            get
            {
                return ResourceManager.GetString("IssuerDownSlm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to در موارد چند تراکنشی، اطلاعات موفقیت از طریق سرویس دیگری ارسال می شود(مخصوص پذیرنده های خاص(.
        /// </summary>
        public static string MultiStateTxn
        {
            get
            {
                return ResourceManager.GetString("MultiStateTxn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to چنین صادر کننده کارتی وجود ندارد.
        /// </summary>
        public static string NoSuchIssuer
        {
            get
            {
                return ResourceManager.GetString("NoSuchIssuer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to موجودی حساب خریدار، کافی نیست.
        /// </summary>
        public static string NoSufficientFunds
        {
            get
            {
                return ResourceManager.GetString("NoSufficientFunds", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to پرداخت با موفقیت انجام شد.
        /// </summary>
        public static string OK
        {
            get
            {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to پرداخت کنسل شده.
        /// </summary>
        public static string PaymentCanceled
        {
            get
            {
                return ResourceManager.GetString("PaymentCanceled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تراکنش در شبکه بانکی Timeout خورده است.
        /// </summary>
        public static string ResponseReceivedTooLate
        {
            get
            {
                return ResourceManager.GetString("ResponseReceivedTooLate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to خطای در پردازش اطلاعات ارسالی (مشکل در یکی از ورودیها و ناموفق بودن فراخوانی متد برگشت تراکنش).
        /// </summary>
        public static string SBNegative1
        {
            get
            {
                return ResourceManager.GetString("SBNegative1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to رسید دیجیتالی به صورت Base64 نیست (حاوی کارکترهای غیرمجاز است).
        /// </summary>
        public static string SBNegative10
        {
            get
            {
                return ResourceManager.GetString("SBNegative10", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to پرداخت کنسل شده.
        /// </summary>
        public static string SBNegative100
        {
            get
            {
                return ResourceManager.GetString("SBNegative100", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to طول ورودی ها کمتر از حد مجاز است.
        /// </summary>
        public static string SBNegative11
        {
            get
            {
                return ResourceManager.GetString("SBNegative11", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to مبلغ برگشتی منفی است.
        /// </summary>
        public static string SBNegative12
        {
            get
            {
                return ResourceManager.GetString("SBNegative12", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to مبلغ برگشتی برای برگشت جزیی بیش از مبلغ برگشت نخورده ی رسید دیجیتالی است.
        /// </summary>
        public static string SBNegative13
        {
            get
            {
                return ResourceManager.GetString("SBNegative13", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to چنین تراکنشی تعریف نشده است.
        /// </summary>
        public static string SBNegative14
        {
            get
            {
                return ResourceManager.GetString("SBNegative14", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to مبلغ برگشتی به صورت اعشاری داده شده است.
        /// </summary>
        public static string SBNegative15
        {
            get
            {
                return ResourceManager.GetString("SBNegative15", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to خطای داخلی سیستم.
        /// </summary>
        public static string SBNegative16
        {
            get
            {
                return ResourceManager.GetString("SBNegative16", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to برگشت زدن جزیی تراکنش مجاز نمی باشد.
        /// </summary>
        public static string SBNegative17
        {
            get
            {
                return ResourceManager.GetString("SBNegative17", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to IP Address فروشنده نامعتبر است.
        /// </summary>
        public static string SBNegative18
        {
            get
            {
                return ResourceManager.GetString("SBNegative18", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ورودی ها حاوی کارکترهای غیرمجاز میباشند.
        /// </summary>
        public static string SBNegative3
        {
            get
            {
                return ResourceManager.GetString("SBNegative3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Merchant Authentication Failed ، کلمه عبور یا کد فروشنده اشتباه است.
        /// </summary>
        public static string SBNegative4
        {
            get
            {
                return ResourceManager.GetString("SBNegative4", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تراکنش قبلا برگشت داده شده است.
        /// </summary>
        public static string SBNegative6
        {
            get
            {
                return ResourceManager.GetString("SBNegative6", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to رسید دیجیتالی تهی است.
        /// </summary>
        public static string SBNegative7
        {
            get
            {
                return ResourceManager.GetString("SBNegative7", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to طول ورودی ها بیشتر از حد مجاز است.
        /// </summary>
        public static string SBNegative8
        {
            get
            {
                return ResourceManager.GetString("SBNegative8", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to وجود کاراکترهای غیرمجاز در مبلغ برگشتی.
        /// </summary>
        public static string SBNegative9
        {
            get
            {
                return ResourceManager.GetString("SBNegative9", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to کاربر در بازه زمانی تعیین شده پاسخی ارسال نکرده است.
        /// </summary>
        public static string SessionIsNull
        {
            get
            {
                return ResourceManager.GetString("SessionIsNull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to کاربر در بازه زمانی تعیین شده پاسخی ارسال نکرده است.
        /// </summary>
        public static string SessionIsNull1
        {
            get
            {
                return ResourceManager.GetString("SessionIsNull1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to خریدار یا فیلد CVV2 و یا فیلد ExpDate را اشتباه وارد کرده است (یا اصلا وارد نکرده است).
        /// </summary>
        public static string SuspectedFraudPickUp
        {
            get
            {
                return ResourceManager.GetString("SuspectedFraudPickUp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to کلیه خطاهای دیگر بانک باعث ایجاد چنین خطایی می گردد.
        /// </summary>
        public static string TMEError
        {
            get
            {
                return ResourceManager.GetString("TMEError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to در موارد چند تراکنشی، تمام تراکنش ها پرداخت ناموفق داشتند.
        /// </summary>
        public static string TotalFailed
        {
            get
            {
                return ResourceManager.GetString("TotalFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to در موارد چند تراکنشی، تمام تراکنش ها پرداخت ناموفق داشتند.
        /// </summary>
        public static string TotalFailed1
        {
            get
            {
                return ResourceManager.GetString("TotalFailed1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تراکنش Authorize شده است (شماره PIN و PAN درست هست) ولی امکان سند خوردن وجود ندارد.
        /// </summary>
        public static string TransactionCannotBeCompleted
        {
            get
            {
                return ResourceManager.GetString("TransactionCannotBeCompleted", resourceCulture);
            }
        }
    }
}
