//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParvazPardaz.Resource.Tour {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tours {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tours() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ParvazPardaz.Resource.Tour.Tours", typeof(Tours).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        public static string Activity {
            get {
                return ResourceManager.GetString("Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Managment.
        /// </summary>
        public static string ActivityManagment {
            get {
                return ResourceManager.GetString("ActivityManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Activity.
        /// </summary>
        public static string AddActivity {
            get {
                return ResourceManager.GetString("AddActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Additional Service.
        /// </summary>
        public static string AddAdditionalService {
            get {
                return ResourceManager.GetString("AddAdditionalService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Airport.
        /// </summary>
        public static string AddAirport {
            get {
                return ResourceManager.GetString("AddAirport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Allowed Banned.
        /// </summary>
        public static string AddAllowedBanned {
            get {
                return ResourceManager.GetString("AddAllowedBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add City.
        /// </summary>
        public static string AddCity {
            get {
                return ResourceManager.GetString("AddCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Company Transfer.
        /// </summary>
        public static string AddCompanyTransfer {
            get {
                return ResourceManager.GetString("AddCompanyTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Company TransferVehicle Type.
        /// </summary>
        public static string AddCompanyTransferVehicleType {
            get {
                return ResourceManager.GetString("AddCompanyTransferVehicleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Country.
        /// </summary>
        public static string AddCountry {
            get {
                return ResourceManager.GetString("AddCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Currency.
        /// </summary>
        public static string AddCurrency {
            get {
                return ResourceManager.GetString("AddCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add FAQ.
        /// </summary>
        public static string AddFAQ {
            get {
                return ResourceManager.GetString("AddFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Flight.
        /// </summary>
        public static string AddFlight {
            get {
                return ResourceManager.GetString("AddFlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Hotel.
        /// </summary>
        public static string AddHotel {
            get {
                return ResourceManager.GetString("AddHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Hotel Facility.
        /// </summary>
        public static string AddHotelFacility {
            get {
                return ResourceManager.GetString("AddHotelFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addhotelPackage.
        /// </summary>
        public static string addhotelPackage {
            get {
                return ResourceManager.GetString("addhotelPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Hotel Rank.
        /// </summary>
        public static string AddHotelRank {
            get {
                return ResourceManager.GetString("AddHotelRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Itinerary.
        /// </summary>
        public static string AddItinerary {
            get {
                return ResourceManager.GetString("AddItinerary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Service.
        /// </summary>
        public static string AdditionalService {
            get {
                return ResourceManager.GetString("AdditionalService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional service management.
        /// </summary>
        public static string AdditionalServiceManagement {
            get {
                return ResourceManager.GetString("AdditionalServiceManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Last Second Tour.
        /// </summary>
        public static string AddLastSecondTour {
            get {
                return ResourceManager.GetString("AddLastSecondTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Leader.
        /// </summary>
        public static string AddLeader {
            get {
                return ResourceManager.GetString("AddLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Required Document.
        /// </summary>
        public static string AddRequiredDocs {
            get {
                return ResourceManager.GetString("AddRequiredDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Schedule.
        /// </summary>
        public static string AddSchedule {
            get {
                return ResourceManager.GetString("AddSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add State.
        /// </summary>
        public static string AddState {
            get {
                return ResourceManager.GetString("AddState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddTour.
        /// </summary>
        public static string AddTour {
            get {
                return ResourceManager.GetString("AddTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Tour Category.
        /// </summary>
        public static string AddTourCategory {
            get {
                return ResourceManager.GetString("AddTourCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Tour Level.
        /// </summary>
        public static string AddTourLevel {
            get {
                return ResourceManager.GetString("AddTourLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddTourPackage.
        /// </summary>
        public static string AddTourPackage {
            get {
                return ResourceManager.GetString("AddTourPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Tour Type.
        /// </summary>
        public static string AddTourType {
            get {
                return ResourceManager.GetString("AddTourType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddVehicleType.
        /// </summary>
        public static string AddVehicleType {
            get {
                return ResourceManager.GetString("AddVehicleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Adult Capacity.
        /// </summary>
        public static string AdultCapacity {
            get {
                return ResourceManager.GetString("AdultCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult Max Capacity.
        /// </summary>
        public static string AdultMaxCapacity {
            get {
                return ResourceManager.GetString("AdultMaxCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult Min Capacity.
        /// </summary>
        public static string AdultMinCapacity {
            get {
                return ResourceManager.GetString("AdultMinCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult Price.
        /// </summary>
        public static string AdultPrice {
            get {
                return ResourceManager.GetString("AdultPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airports.
        /// </summary>
        public static string Airports {
            get {
                return ResourceManager.GetString("Airports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed Banned.
        /// </summary>
        public static string AllowedBanned {
            get {
                return ResourceManager.GetString("AllowedBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed and Banned Management.
        /// </summary>
        public static string AllowedBannedManagement {
            get {
                return ResourceManager.GetString("AllowedBannedManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows.
        /// </summary>
        public static string Allows {
            get {
                return ResourceManager.GetString("Allows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival Date.
        /// </summary>
        public static string ArrivalDate {
            get {
                return ResourceManager.GetString("ArrivalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArrivalTime.
        /// </summary>
        public static string ArrivalTime {
            get {
                return ResourceManager.GetString("ArrivalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bans.
        /// </summary>
        public static string Bans {
            get {
                return ResourceManager.GetString("Bans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Rial Price.
        /// </summary>
        public static string BaseRialPrice {
            get {
                return ResourceManager.GetString("BaseRialPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Update Price In Tour Package.
        /// </summary>
        public static string BatchUpdatePriceInTourPackage {
            get {
                return ResourceManager.GetString("BatchUpdatePriceInTourPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Now.
        /// </summary>
        public static string BookNow {
            get {
                return ResourceManager.GetString("BookNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        public static string Capacity {
            get {
                return ResourceManager.GetString("Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Child Capacity.
        /// </summary>
        public static string ChildCapacity {
            get {
                return ResourceManager.GetString("ChildCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Max Capacity.
        /// </summary>
        public static string ChildMaxCapacity {
            get {
                return ResourceManager.GetString("ChildMaxCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Min Capacity.
        /// </summary>
        public static string ChildMinCapacity {
            get {
                return ResourceManager.GetString("ChildMinCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Price.
        /// </summary>
        public static string ChildPrice {
            get {
                return ResourceManager.GetString("ChildPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City management.
        /// </summary>
        public static string CityManagement {
            get {
                return ResourceManager.GetString("CityManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Title.
        /// </summary>
        public static string CityTitle {
            get {
                return ResourceManager.GetString("CityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Transfer.
        /// </summary>
        public static string CompanyTransfer {
            get {
                return ResourceManager.GetString("CompanyTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Transfer Management.
        /// </summary>
        public static string CompanyTransferManagement {
            get {
                return ResourceManager.GetString("CompanyTransferManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Transfer Vehicle Type.
        /// </summary>
        public static string CompanyTransferVehicleType {
            get {
                return ResourceManager.GetString("CompanyTransferVehicleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Transfer Vehicle Management.
        /// </summary>
        public static string CompanyTransferVehicleTypeManagement {
            get {
                return ResourceManager.GetString("CompanyTransferVehicleTypeManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country management.
        /// </summary>
        public static string CountryManagement {
            get {
                return ResourceManager.GetString("CountryManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency management.
        /// </summary>
        public static string CurrencyManagement {
            get {
                return ResourceManager.GetString("CurrencyManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Update Price Value.
        /// </summary>
        public static string CurrencyUpdatePriceVal {
            get {
                return ResourceManager.GetString("CurrencyUpdatePriceVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curreny Sign.
        /// </summary>
        public static string CurrenySign {
            get {
                return ResourceManager.GetString("CurrenySign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTitle.
        /// </summary>
        public static string DateTitle {
            get {
                return ResourceManager.GetString("DateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DayOrder.
        /// </summary>
        public static string DayOrder {
            get {
                return ResourceManager.GetString("DayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Title.
        /// </summary>
        public static string DayTitle {
            get {
                return ResourceManager.GetString("DayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure Date.
        /// </summary>
        public static string DepartureDate {
            get {
                return ResourceManager.GetString("DepartureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure Time.
        /// </summary>
        public static string DepartureTime {
            get {
                return ResourceManager.GetString("DepartureTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Airport.
        /// </summary>
        public static string DestinationAirport {
            get {
                return ResourceManager.GetString("DestinationAirport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination City.
        /// </summary>
        public static string DestinationCity {
            get {
                return ResourceManager.GetString("DestinationCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discounted Tour.
        /// </summary>
        public static string DiscountedTour {
            get {
                return ResourceManager.GetString("DiscountedTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DurationDay.
        /// </summary>
        public static string DurationDay {
            get {
                return ResourceManager.GetString("DurationDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration Time.
        /// </summary>
        public static string DurationTime {
            get {
                return ResourceManager.GetString("DurationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Hotel Gallery.
        /// </summary>
        public static string EditHotelGallery {
            get {
                return ResourceManager.GetString("EditHotelGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title (en).
        /// </summary>
        public static string ENTitle {
            get {
                return ResourceManager.GetString("ENTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum Update Price Type.
        /// </summary>
        public static string EnumUpdatePriceType {
            get {
                return ResourceManager.GetString("EnumUpdatePriceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire Date.
        /// </summary>
        public static string ExpireDate {
            get {
                return ResourceManager.GetString("ExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ Management.
        /// </summary>
        public static string FAQManagement {
            get {
                return ResourceManager.GetString("FAQManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Tours.
        /// </summary>
        public static string FetchTours {
            get {
                return ResourceManager.GetString("FetchTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch Tours By Tour Groups.
        /// </summary>
        public static string FetchToursByTourGroup {
            get {
                return ResourceManager.GetString("FetchToursByTourGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlightClass.
        /// </summary>
        public static string FlightClass {
            get {
                return ResourceManager.GetString("FlightClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlightNumber.
        /// </summary>
        public static string FlightNumber {
            get {
                return ResourceManager.GetString("FlightNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For discount tour.
        /// </summary>
        public static string ForDiscountTour {
            get {
                return ResourceManager.GetString("ForDiscountTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For general tour.
        /// </summary>
        public static string ForGeneralTour {
            get {
                return ResourceManager.GetString("ForGeneralTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Airport.
        /// </summary>
        public static string FromAirport {
            get {
                return ResourceManager.GetString("FromAirport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FromCity.
        /// </summary>
        public static string FromCity {
            get {
                return ResourceManager.GetString("FromCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Price.
        /// </summary>
        public static string FromPrice {
            get {
                return ResourceManager.GetString("FromPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Tour.
        /// </summary>
        public static string GeneralTour {
            get {
                return ResourceManager.GetString("GeneralTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        public static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Index.
        /// </summary>
        public static string GoToIndex {
            get {
                return ResourceManager.GetString("GoToIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Adult?.
        /// </summary>
        public static string HasAdult {
            get {
                return ResourceManager.GetString("HasAdult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Child?.
        /// </summary>
        public static string HasChild {
            get {
                return ResourceManager.GetString("HasChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Infant?.
        /// </summary>
        public static string HasInfant {
            get {
                return ResourceManager.GetString("HasInfant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Image.
        /// </summary>
        public static string HeaderImage {
            get {
                return ResourceManager.GetString("HeaderImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel.
        /// </summary>
        public static string Hotel {
            get {
                return ResourceManager.GetString("Hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Board.
        /// </summary>
        public static string HotelBoard {
            get {
                return ResourceManager.GetString("HotelBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Facility.
        /// </summary>
        public static string HotelFacility {
            get {
                return ResourceManager.GetString("HotelFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Facility Management.
        /// </summary>
        public static string HotelFacilityManagement {
            get {
                return ResourceManager.GetString("HotelFacilityManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Gallery Management.
        /// </summary>
        public static string HotelGalleryManagement {
            get {
                return ResourceManager.GetString("HotelGalleryManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Location.
        /// </summary>
        public static string HotelLocation {
            get {
                return ResourceManager.GetString("HotelLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Management.
        /// </summary>
        public static string HotelManagement {
            get {
                return ResourceManager.GetString("HotelManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Rank.
        /// </summary>
        public static string HotelRank {
            get {
                return ResourceManager.GetString("HotelRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Rank Management.
        /// </summary>
        public static string HotelRankManagement {
            get {
                return ResourceManager.GetString("HotelRankManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Rank Managment.
        /// </summary>
        public static string HotelRankManagment {
            get {
                return ResourceManager.GetString("HotelRankManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Room.
        /// </summary>
        public static string HotelRoom {
            get {
                return ResourceManager.GetString("HotelRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Room Management.
        /// </summary>
        public static string HotelRoomManagement {
            get {
                return ResourceManager.GetString("HotelRoomManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Title.
        /// </summary>
        public static string HotelTitle {
            get {
                return ResourceManager.GetString("HotelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IATA Code.
        /// </summary>
        public static string IataCode {
            get {
                return ResourceManager.GetString("IataCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image file name.
        /// </summary>
        public static string ImageFileName {
            get {
                return ResourceManager.GetString("ImageFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images Gallery.
        /// </summary>
        public static string ImagesGallery {
            get {
                return ResourceManager.GetString("ImagesGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageURL.
        /// </summary>
        public static string ImageURL {
            get {
                return ResourceManager.GetString("ImageURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Infant Capacity.
        /// </summary>
        public static string InfantCapacity {
            get {
                return ResourceManager.GetString("InfantCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infant Max Capacity.
        /// </summary>
        public static string InfantMaxCapacity {
            get {
                return ResourceManager.GetString("InfantMaxCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infant Min Capacity.
        /// </summary>
        public static string InfantMinCapacity {
            get {
                return ResourceManager.GetString("InfantMinCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infant Price.
        /// </summary>
        public static string InfantPrice {
            get {
                return ResourceManager.GetString("InfantPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iran Update Price Value.
        /// </summary>
        public static string IranUpdatePriceVal {
            get {
                return ResourceManager.GetString("IranUpdatePriceVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active?.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is available for select?.
        /// </summary>
        public static string IsAvailable {
            get {
                return ResourceManager.GetString("IsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsDddlDestination.
        /// </summary>
        public static string IsDddlDestination {
            get {
                return ResourceManager.GetString("IsDddlDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsDddlFrom.
        /// </summary>
        public static string IsDddlFrom {
            get {
                return ResourceManager.GetString("IsDddlFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Primary?.
        /// </summary>
        public static string IsPrimary {
            get {
                return ResourceManager.GetString("IsPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make fast?.
        /// </summary>
        public static string IsSummary {
            get {
                return ResourceManager.GetString("IsSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Update Currency Price.
        /// </summary>
        public static string IsUpdateCurrencyPrice {
            get {
                return ResourceManager.GetString("IsUpdateCurrencyPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour url type.
        /// </summary>
        public static string LandingPageUrlType {
            get {
                return ResourceManager.GetString("LandingPageUrlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Second Tour .
        /// </summary>
        public static string LastSecondTour {
            get {
                return ResourceManager.GetString("LastSecondTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google map.
        /// </summary>
        public static string LatLongIframe {
            get {
                return ResourceManager.GetString("LatLongIframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leader.
        /// </summary>
        public static string Leader {
            get {
                return ResourceManager.GetString("Leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leader Management.
        /// </summary>
        public static string LeaderManagement {
            get {
                return ResourceManager.GetString("LeaderManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string LinkTableTitle {
            get {
                return ResourceManager.GetString("LinkTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landing.
        /// </summary>
        public static string LocationId {
            get {
                return ResourceManager.GetString("LocationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Of Airports.
        /// </summary>
        public static string ManagementAirport {
            get {
                return ResourceManager.GetString("ManagementAirport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Of Content Groups.
        /// </summary>
        public static string ManagementContentGroup {
            get {
                return ResourceManager.GetString("ManagementContentGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management of Hotel Board.
        /// </summary>
        public static string ManagementHotelBoard {
            get {
                return ResourceManager.GetString("ManagementHotelBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management of hotel rules.
        /// </summary>
        public static string ManagementHotelRules {
            get {
                return ResourceManager.GetString("ManagementHotelRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Of Last Second Tours.
        /// </summary>
        public static string ManagementLastSecondTours {
            get {
                return ResourceManager.GetString("ManagementLastSecondTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Of Not Fount Links 404.
        /// </summary>
        public static string ManagementNotFountLinks {
            get {
                return ResourceManager.GetString("ManagementNotFountLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management of Tours Required Documents.
        /// </summary>
        public static string ManagementTourRequiredDocs {
            get {
                return ResourceManager.GetString("ManagementTourRequiredDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Of Vehicle Type Class.
        /// </summary>
        public static string ManagementVehicleTypeClass {
            get {
                return ResourceManager.GetString("ManagementVehicleTypeClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model name.
        /// </summary>
        public static string ModelName {
            get {
                return ResourceManager.GetString("ModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NavigationUrl.
        /// </summary>
        public static string NavigationUrl {
            get {
                return ResourceManager.GetString("NavigationUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Limit.
        /// </summary>
        public static string NonLimit {
            get {
                return ResourceManager.GetString("NonLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowruz Tours.
        /// </summary>
        public static string NowruzTours {
            get {
                return ResourceManager.GetString("NowruzTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric.
        /// </summary>
        public static string Numeric {
            get {
                return ResourceManager.GetString("Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfferPrice.
        /// </summary>
        public static string OfferPrice {
            get {
                return ResourceManager.GetString("OfferPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderHotelPackage.
        /// </summary>
        public static string OrderHotelPackage {
            get {
                return ResourceManager.GetString("OrderHotelPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OwnerId.
        /// </summary>
        public static string OwnerId {
            get {
                return ResourceManager.GetString("OwnerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PackageManagement.
        /// </summary>
        public static string PackageManagement {
            get {
                return ResourceManager.GetString("PackageManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent.
        /// </summary>
        public static string Percent {
            get {
                return ResourceManager.GetString("Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        public static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        public static string PersonUnit {
            get {
                return ResourceManager.GetString("PersonUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture size in width 100 and height 100..
        /// </summary>
        public static string PicSize100x100 {
            get {
                return ResourceManager.GetString("PicSize100x100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture size in width 200 and height 200..
        /// </summary>
        public static string PicSize200x200 {
            get {
                return ResourceManager.GetString("PicSize200x200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture size in width 447 and height 342..
        /// </summary>
        public static string PicSizeActivity {
            get {
                return ResourceManager.GetString("PicSizeActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to picture in width 700 and height 525..
        /// </summary>
        public static string PicSizeHotel {
            get {
                return ResourceManager.GetString("PicSizeHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Notice!&lt;/strong&gt; Picture size in width &lt;code&gt;447&lt;/code&gt;and height &lt;code&gt;342&lt;/code&gt; pixel.
        /// </summary>
        public static string PicSizeLastSecondTour {
            get {
                return ResourceManager.GetString("PicSizeLastSecondTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture size in width 1280 and height 573..
        /// </summary>
        public static string PicSizeSlider {
            get {
                return ResourceManager.GetString("PicSizeSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture size in width 835 and height 500. .
        /// </summary>
        public static string PicSizeTourPrimarySlider {
            get {
                return ResourceManager.GetString("PicSizeTourPrimarySlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        public static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        public static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active?.
        /// </summary>
        public static string Recomended {
            get {
                return ResourceManager.GetString("Recomended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Documents.
        /// </summary>
        public static string RequiredDocuments {
            get {
                return ResourceManager.GetString("RequiredDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale.
        /// </summary>
        public static string Sale {
            get {
                return ResourceManager.GetString("Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaleManagement.
        /// </summary>
        public static string SaleManagement {
            get {
                return ResourceManager.GetString("SaleManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SarinaPrice.
        /// </summary>
        public static string SarinaPrice {
            get {
                return ResourceManager.GetString("SarinaPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select At Least One Element.
        /// </summary>
        public static string SelectAtLeastOneElement {
            get {
                return ResourceManager.GetString("SelectAtLeastOneElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Select Company Transfer ---.
        /// </summary>
        public static string SelectCompanyTransfer {
            get {
                return ResourceManager.GetString("SelectCompanyTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Picture.
        /// </summary>
        public static string SelectPic {
            get {
                return ResourceManager.GetString("SelectPic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Select Vehicle Type ---.
        /// </summary>
        public static string SelectVehicleType {
            get {
                return ResourceManager.GetString("SelectVehicleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seo text.
        /// </summary>
        public static string SeoText {
            get {
                return ResourceManager.GetString("SeoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Description.
        /// </summary>
        public static string ServiceDesc {
            get {
                return ResourceManager.GetString("ServiceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share It.
        /// </summary>
        public static string Shareit {
            get {
                return ResourceManager.GetString("Shareit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Code.
        /// </summary>
        public static string ShortCode {
            get {
                return ResourceManager.GetString("ShortCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Description.
        /// </summary>
        public static string ShortDescription {
            get {
                return ResourceManager.GetString("ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sold Quantity.
        /// </summary>
        public static string SoldQuantity {
            get {
                return ResourceManager.GetString("SoldQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure.
        /// </summary>
        public static string StartDateTime {
            get {
                return ResourceManager.GetString("StartDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State management.
        /// </summary>
        public static string StateManagement {
            get {
                return ResourceManager.GetString("StateManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iata Code.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult Capacity.
        /// </summary>
        public static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel.
        /// </summary>
        public static string Tel {
            get {
                return ResourceManager.GetString("Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title(EN).
        /// </summary>
        public static string TitleEn {
            get {
                return ResourceManager.GetString("TitleEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour.
        /// </summary>
        public static string Tour {
            get {
                return ResourceManager.GetString("Tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Category.
        /// </summary>
        public static string TourCategory {
            get {
                return ResourceManager.GetString("TourCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Category Management.
        /// </summary>
        public static string TourCategoryManagement {
            get {
                return ResourceManager.GetString("TourCategoryManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Code.
        /// </summary>
        public static string TourCode {
            get {
                return ResourceManager.GetString("TourCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TourDuration.
        /// </summary>
        public static string TourDuration {
            get {
                return ResourceManager.GetString("TourDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Group.
        /// </summary>
        public static string TourGroup {
            get {
                return ResourceManager.GetString("TourGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Landing Page.
        /// </summary>
        public static string TourLandingPage {
            get {
                return ResourceManager.GetString("TourLandingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /tour/country-city-airfloot-offer/.
        /// </summary>
        public static string TourLandingPageUrlPatternForDiscountTour {
            get {
                return ResourceManager.GetString("TourLandingPageUrlPatternForDiscountTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /tour/country-city-season-airfloot/.
        /// </summary>
        public static string TourLandingPageUrlPatternForGeneralTour {
            get {
                return ResourceManager.GetString("TourLandingPageUrlPatternForGeneralTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Level.
        /// </summary>
        public static string TourLevel {
            get {
                return ResourceManager.GetString("TourLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Level Management.
        /// </summary>
        public static string TourLevelManagement {
            get {
                return ResourceManager.GetString("TourLevelManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TourManagement.
        /// </summary>
        public static string TourManagement {
            get {
                return ResourceManager.GetString("TourManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Pacage From Price.
        /// </summary>
        public static string TourPacageFromPrice {
            get {
                return ResourceManager.GetString("TourPacageFromPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Package.
        /// </summary>
        public static string TourPackage {
            get {
                return ResourceManager.GetString("TourPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TourPackageDayManagement.
        /// </summary>
        public static string TourPackageDayManagement {
            get {
                return ResourceManager.GetString("TourPackageDayManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TourPackageTitle.
        /// </summary>
        public static string TourPackageTitle {
            get {
                return ResourceManager.GetString("TourPackageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TourPackgeDayId.
        /// </summary>
        public static string TourPackgeDayId {
            get {
                return ResourceManager.GetString("TourPackgeDayId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Priority Management.
        /// </summary>
        public static string TourPriorityManagement {
            get {
                return ResourceManager.GetString("TourPriorityManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Schedule.
        /// </summary>
        public static string TourSchedule {
            get {
                return ResourceManager.GetString("TourSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tours.
        /// </summary>
        public static string ToursList {
            get {
                return ResourceManager.GetString("ToursList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TourSuggestManagement.
        /// </summary>
        public static string TourSuggestManagement {
            get {
                return ResourceManager.GetString("TourSuggestManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Title.
        /// </summary>
        public static string TourTitle {
            get {
                return ResourceManager.GetString("TourTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Type.
        /// </summary>
        public static string TourType {
            get {
                return ResourceManager.GetString("TourType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Type Management.
        /// </summary>
        public static string TourTypeManagement {
            get {
                return ResourceManager.GetString("TourTypeManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        public static string Transaction {
            get {
                return ResourceManager.GetString("Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Management.
        /// </summary>
        public static string TransactionManagement {
            get {
                return ResourceManager.GetString("TransactionManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportation.
        /// </summary>
        public static string Transportation {
            get {
                return ResourceManager.GetString("Transportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Itinerary.
        /// </summary>
        public static string UpdateItinerary {
            get {
                return ResourceManager.GetString("UpdateItinerary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Schedule.
        /// </summary>
        public static string UpdateSchedule {
            get {
                return ResourceManager.GetString("UpdateSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateTourPackage.
        /// </summary>
        public static string UpdateTourPackage {
            get {
                return ResourceManager.GetString("UpdateTourPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link 404 Address.
        /// </summary>
        public static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select tour&apos;s url.
        /// </summary>
        public static string UrlRequired {
            get {
                return ResourceManager.GetString("UrlRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن سئو در تب های مجله گردشگری مورد استفاده قرار خواهد گرفت.
        /// </summary>
        public static string UsedForTabMagazineSeo {
            get {
                return ResourceManager.GetString("UsedForTabMagazineSeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used In Tour.
        /// </summary>
        public static string UsedInTour {
            get {
                return ResourceManager.GetString("UsedInTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا URL را مطابق الگوی زیر ، با استفاده از کلمات انگلیسی و (نگارش صحیح) بسازید.
        /// </summary>
        public static string UseThisTourLandingPageUrlPattern {
            get {
                return ResourceManager.GetString("UseThisTourLandingPageUrlPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Type.
        /// </summary>
        public static string VehicleType {
            get {
                return ResourceManager.GetString("VehicleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Type Class.
        /// </summary>
        public static string VehicleTypeClass {
            get {
                return ResourceManager.GetString("VehicleTypeClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Type.
        /// </summary>
        public static string VehicleTypeId {
            get {
                return ResourceManager.GetString("VehicleTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Type Mangement.
        /// </summary>
        public static string VehicleTypeMangement {
            get {
                return ResourceManager.GetString("VehicleTypeMangement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
    }
}
